// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class ElemAttribRef {
    protected java.lang.String country;
    protected org.jboss.ws.types.Employee USEmployee;
    protected org.jboss.ws.types.Address USAddress;

    public ElemAttribRef() {
    }

    public ElemAttribRef(java.lang.String country, org.jboss.ws.types.Employee USEmployee, org.jboss.ws.types.Address USAddress) {
        this.country = country;
        this.USEmployee = USEmployee;
        this.USAddress = USAddress;
    }

    public java.lang.String getCountry() {
        return country;
    }

    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    public org.jboss.ws.types.Employee getUSEmployee() {
        return USEmployee;
    }

    public void setUSEmployee(org.jboss.ws.types.Employee USEmployee) {
        this.USEmployee = USEmployee;
    }

    public org.jboss.ws.types.Address getUSAddress() {
        return USAddress;
    }

    public void setUSAddress(org.jboss.ws.types.Address USAddress) {
        this.USAddress = USAddress;
    }
}