// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class Employee {
    protected java.lang.String name;
    protected java.lang.String role;
    protected java.lang.String boss;

    public Employee() {
    }

    public Employee(java.lang.String name, java.lang.String role, java.lang.String boss) {
        this.name = name;
        this.role = role;
        this.boss = boss;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getRole() {
        return role;
    }

    public void setRole(java.lang.String role) {
        this.role = role;
    }

    public java.lang.String getBoss() {
        return boss;
    }

    public void setBoss(java.lang.String boss) {
        this.boss = boss;
    }
}