package org.jboss.test.ws.jaxws.jbws1172.types;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0-SNAPSHOT
 * 2012-07-17T00:38:10.376+08:00
 * Generated source version: 2.6.0-SNAPSHOT
 * 
 */
@WebService(targetNamespace = "http://www.my-company.it/ws/my-test", name = "MyTest")
@XmlSeeAlso({ObjectFactory.class})
public interface MyTest {

    @RequestWrapper(localName = "performTest", targetNamespace = "http://www.my-company.it/ws/my-test", className = "org.jboss.test.ws.jaxws.jbws1172.types.PerformTest")
    @WebMethod(action = "urn:performTest")
    @ResponseWrapper(localName = "performTestResponse", targetNamespace = "http://www.my-company.it/ws/my-test", className = "org.jboss.test.ws.jaxws.jbws1172.types.PerformTestResponse")
    public void performTest(
        @WebParam(name = "Code", targetNamespace = "")
        java.lang.Integer code
    ) throws MyWSException_Exception;
}
