
package org.jboss.test.ws.jaxws.jbws1172.types;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0-SNAPSHOT
 * 2012-07-17T00:38:10.286+08:00
 * Generated source version: 2.6.0-SNAPSHOT
 */

@WebFault(name = "MyWSException", targetNamespace = "http://www.my-company.it/ws/my-test")
public class MyWSException_Exception extends Exception {
    
    private org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException;

    public MyWSException_Exception() {
        super();
    }
    
    public MyWSException_Exception(String message) {
        super(message);
    }
    
    public MyWSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MyWSException_Exception(String message, org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException) {
        super(message);
        this.myWSException = myWSException;
    }

    public MyWSException_Exception(String message, org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException, Throwable cause) {
        super(message, cause);
        this.myWSException = myWSException;
    }

    public org.jboss.test.ws.jaxws.jbws1172.types.MyWSException getFaultInfo() {
        return this.myWSException;
    }
}
