/*
 * JBoss, Home of Professional Open Source.
 * Copyright 2012, Red Hat Middleware LLC, and individual contributors
 * as indicated by the @author tags. See the copyright.txt file in the
 * distribution for a full listing of individual contributors.
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 2.1 of
 * the License, or (at your option) any later version.
 *
 * This software is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this software; if not, write to the Free
 * Software Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA, or see the FSF site: http://www.fsf.org.
 */
package org.jboss.test.ws.jaxws.jbws1172.types;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.0-SNAPSHOT
 * 2012-07-17T00:38:10.286+08:00
 * Generated source version: 2.6.0-SNAPSHOT
 */

@WebFault(name = "MyWSException", targetNamespace = "http://www.my-company.it/ws/my-test")
public class MyWSException_Exception extends Exception {
    
    private org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException;

    public MyWSException_Exception() {
        super();
    }
    
    public MyWSException_Exception(String message) {
        super(message);
    }
    
    public MyWSException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public MyWSException_Exception(String message, org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException) {
        super(message);
        this.myWSException = myWSException;
    }

    public MyWSException_Exception(String message, org.jboss.test.ws.jaxws.jbws1172.types.MyWSException myWSException, Throwable cause) {
        super(message, cause);
        this.myWSException = myWSException;
    }

    public org.jboss.test.ws.jaxws.jbws1172.types.MyWSException getFaultInfo() {
        return this.myWSException;
    }
}
