
package org.jboss.test.ws.jaxws.jbws1172.types;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "MyWSException", targetNamespace = "http://www.my-company.it/ws/my-test")
public class MyWSException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MyWSException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MyWSException_Exception(String message, MyWSException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public MyWSException_Exception(String message, MyWSException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.jboss.test.ws.jaxws.jbws1172.types.MyWSException
     */
    public MyWSException getFaultInfo() {
        return faultInfo;
    }

}
