// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class LookupResponse {
    protected java.lang.String postcode;
    protected java.lang.String number;
    
    public LookupResponse() {
    }
    
    public LookupResponse(java.lang.String postcode, java.lang.String number) {
        this.postcode = postcode;
        this.number = number;
    }
    
    public java.lang.String getPostcode() {
        return postcode;
    }
    
    public void setPostcode(java.lang.String postcode) {
        this.postcode = postcode;
    }
    
    public java.lang.String getNumber() {
        return number;
    }
    
    public void setNumber(java.lang.String number) {
        this.number = number;
    }
}
