// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetLong_ResponseStruct {
    protected long retLongResult;
    
    public IBaseDataTypesRpcLit_RetLong_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetLong_ResponseStruct(long retLongResult) {
        this.retLongResult = retLongResult;
    }
    
    public long getRetLongResult() {
        return retLongResult;
    }
    
    public void setRetLongResult(long retLongResult) {
        this.retLongResult = retLongResult;
    }
}
