// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetULong_ResponseStruct {
    protected java.math.BigInteger retULongResult;
    
    public IBaseDataTypesRpcLit_RetULong_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetULong_ResponseStruct(java.math.BigInteger retULongResult) {
        this.retULongResult = retULongResult;
    }
    
    public java.math.BigInteger getRetULongResult() {
        return retULongResult;
    }
    
    public void setRetULongResult(java.math.BigInteger retULongResult) {
        this.retULongResult = retULongResult;
    }
}
