// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetGuid_ResponseStruct {
    protected java.lang.String retGuidResult;
    
    public IBaseDataTypesRpcLit_RetGuid_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetGuid_ResponseStruct(java.lang.String retGuidResult) {
        this.retGuidResult = retGuidResult;
    }
    
    public java.lang.String getRetGuidResult() {
        return retGuidResult;
    }
    
    public void setRetGuidResult(java.lang.String retGuidResult) {
        this.retGuidResult = retGuidResult;
    }
}
