// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetChar_RequestStruct {
    protected int inChar;
    
    public IBaseDataTypesRpcLit_RetChar_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetChar_RequestStruct(int inChar) {
        this.inChar = inChar;
    }
    
    public int getInChar() {
        return inChar;
    }
    
    public void setInChar(int inChar) {
        this.inChar = inChar;
    }
}
