// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetUInt_ResponseStruct {
    protected long retUIntResult;
    
    public IBaseDataTypesRpcLit_RetUInt_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetUInt_ResponseStruct(long retUIntResult) {
        this.retUIntResult = retUIntResult;
    }
    
    public long getRetUIntResult() {
        return retUIntResult;
    }
    
    public void setRetUIntResult(long retUIntResult) {
        this.retUIntResult = retUIntResult;
    }
}
