// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetUri_ResponseStruct {
    protected java.net.URI retUriResult;
    
    public IBaseDataTypesRpcLit_RetUri_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetUri_ResponseStruct(java.net.URI retUriResult) {
        this.retUriResult = retUriResult;
    }
    
    public java.net.URI getRetUriResult() {
        return retUriResult;
    }
    
    public void setRetUriResult(java.net.URI retUriResult) {
        this.retUriResult = retUriResult;
    }
}
