// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetDateTime_RequestStruct {
    protected java.util.Calendar inDateTime;
    
    public IBaseDataTypesRpcLit_RetDateTime_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetDateTime_RequestStruct(java.util.Calendar inDateTime) {
        this.inDateTime = inDateTime;
    }
    
    public java.util.Calendar getInDateTime() {
        return inDateTime;
    }
    
    public void setInDateTime(java.util.Calendar inDateTime) {
        this.inDateTime = inDateTime;
    }
}
