// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetSByte_RequestStruct {
    protected byte inSByte;
    
    public IBaseDataTypesRpcLit_RetSByte_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetSByte_RequestStruct(byte inSByte) {
        this.inSByte = inSByte;
    }
    
    public byte getInSByte() {
        return inSByte;
    }
    
    public void setInSByte(byte inSByte) {
        this.inSByte = inSByte;
    }
}
