// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetString_ResponseStruct {
    protected java.lang.String retStringResult;
    
    public IBaseDataTypesRpcLit_RetString_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetString_ResponseStruct(java.lang.String retStringResult) {
        this.retStringResult = retStringResult;
    }
    
    public java.lang.String getRetStringResult() {
        return retStringResult;
    }
    
    public void setRetStringResult(java.lang.String retStringResult) {
        this.retStringResult = retStringResult;
    }
}
