// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetSByte_ResponseStruct {
    protected byte retSByteResult;
    
    public IBaseDataTypesRpcLit_RetSByte_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetSByte_ResponseStruct(byte retSByteResult) {
        this.retSByteResult = retSByteResult;
    }
    
    public byte getRetSByteResult() {
        return retSByteResult;
    }
    
    public void setRetSByteResult(byte retSByteResult) {
        this.retSByteResult = retSByteResult;
    }
}
