// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetTimeSpan_RequestStruct {
    protected java.lang.String inTimeSpan;
    
    public IBaseDataTypesRpcLit_RetTimeSpan_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetTimeSpan_RequestStruct(java.lang.String inTimeSpan) {
        this.inTimeSpan = inTimeSpan;
    }
    
    public java.lang.String getInTimeSpan() {
        return inTimeSpan;
    }
    
    public void setInTimeSpan(java.lang.String inTimeSpan) {
        this.inTimeSpan = inTimeSpan;
    }
}
