// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetQName_ResponseStruct {
    protected javax.xml.namespace.QName retQNameResult;
    
    public IBaseDataTypesRpcLit_RetQName_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetQName_ResponseStruct(javax.xml.namespace.QName retQNameResult) {
        this.retQNameResult = retQNameResult;
    }
    
    public javax.xml.namespace.QName getRetQNameResult() {
        return retQNameResult;
    }
    
    public void setRetQNameResult(javax.xml.namespace.QName retQNameResult) {
        this.retQNameResult = retQNameResult;
    }
}
