// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetByte_RequestStruct {
    protected short inByte;
    
    public IBaseDataTypesRpcLit_RetByte_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetByte_RequestStruct(short inByte) {
        this.inByte = inByte;
    }
    
    public short getInByte() {
        return inByte;
    }
    
    public void setInByte(short inByte) {
        this.inByte = inByte;
    }
}
