// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetShort_RequestStruct {
    protected short inShort;
    
    public IBaseDataTypesRpcLit_RetShort_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetShort_RequestStruct(short inShort) {
        this.inShort = inShort;
    }
    
    public short getInShort() {
        return inShort;
    }
    
    public void setInShort(short inShort) {
        this.inShort = inShort;
    }
}
