// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetObject_ResponseStruct {
    protected javax.xml.soap.SOAPElement retObjectResult;
    
    public IBaseDataTypesRpcLit_RetObject_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetObject_ResponseStruct(javax.xml.soap.SOAPElement retObjectResult) {
        this.retObjectResult = retObjectResult;
    }
    
    public javax.xml.soap.SOAPElement getRetObjectResult() {
        return retObjectResult;
    }
    
    public void setRetObjectResult(javax.xml.soap.SOAPElement retObjectResult) {
        this.retObjectResult = retObjectResult;
    }
}
