// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetFloat_RequestStruct {
    protected float inFloat;
    
    public IBaseDataTypesRpcLit_RetFloat_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetFloat_RequestStruct(float inFloat) {
        this.inFloat = inFloat;
    }
    
    public float getInFloat() {
        return inFloat;
    }
    
    public void setInFloat(float inFloat) {
        this.inFloat = inFloat;
    }
}
