// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit_Service;


public class IBaseDataTypesRpcLit_RetFloat_ResponseStruct {
    protected float retFloatResult;
    
    public IBaseDataTypesRpcLit_RetFloat_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetFloat_ResponseStruct(float retFloatResult) {
        this.retFloatResult = retFloatResult;
    }
    
    public float getRetFloatResult() {
        return retFloatResult;
    }
    
    public void setRetFloatResult(float retFloatResult) {
        this.retFloatResult = retFloatResult;
    }
}
