// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1259;


public class Person {
    protected java.lang.String firstName;
    protected java.lang.String surname;
    protected org.jboss.test.ws.jbws1259.Comment comment;
    
    public Person() {
    }
    
    public Person(java.lang.String firstName, java.lang.String surname, org.jboss.test.ws.jbws1259.Comment comment) {
        this.firstName = firstName;
        this.surname = surname;
        this.comment = comment;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getSurname() {
        return surname;
    }
    
    public void setSurname(java.lang.String surname) {
        this.surname = surname;
    }
    
    public org.jboss.test.ws.jbws1259.Comment getComment() {
        return comment;
    }
    
    public void setComment(org.jboss.test.ws.jbws1259.Comment comment) {
        this.comment = comment;
    }
}
