/*
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org.
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.wsse;


public class  JaxRpcTestService_echoSimpleUserType_RequestStruct
{

protected java.lang.String String_1;

protected SimpleUserType SimpleUserType_2;
public JaxRpcTestService_echoSimpleUserType_RequestStruct(){}

public JaxRpcTestService_echoSimpleUserType_RequestStruct(java.lang.String String_1,SimpleUserType SimpleUserType_2){
this.String_1=String_1;
this.SimpleUserType_2=SimpleUserType_2;
}
public java.lang.String getString_1() { return String_1 ;}

public void setString_1(java.lang.String myvar ){  String_1=myvar ;}

public SimpleUserType getSimpleUserType_2() { return SimpleUserType_2 ;}

public void setSimpleUserType_2(SimpleUserType myvar ){  SimpleUserType_2=myvar ;}

}
