// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws810;

public interface PhoneBook_PortType extends java.rmi.Remote {
    public java.lang.String lookup(java.lang.String person_1) throws 
         java.rmi.RemoteException;
}
