
package org.jboss.test.ws.jaxws.samples.webparam;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.WebParam.Mode;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "PingService", targetNamespace = "http://www.openuri.org/jsr181/WebParamExample", wsdlLocation = "META-INF/wsdl/PingService.wsdl")
@SOAPBinding(style = Style.RPC)
public interface PingService {


    /**
     * 
     * @param ping
     */
    @WebMethod(operationName = "PingOneWay")
    @Oneway
    public void pingOneWay(
        @WebParam(name = "Ping", partName = "Ping")
        PingDocument ping);

    /**
     * 
     * @param ping
     */
    @WebMethod(operationName = "PingTwoWay")
    public void pingTwoWay(
        @WebParam(name = "Ping", mode = Mode.INOUT, partName = "Ping")
        Holder<PingDocument> ping);

    /**
     * 
     * @param secHeader
     * @param ping
     */
    @WebMethod(operationName = "SecurePing")
    @Oneway
    public void securePing(
        @WebParam(name = "Ping", partName = "Ping")
        PingDocument ping,
        @WebParam(name = "SecHeader", targetNamespace = "http://www.openuri.org/jsr181/WebParamExample", header = true, partName = "SecHeader")
        SecurityHeader secHeader);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.jboss.test.ws.jaxws.samples.webparam.PingDocument
     */
    @WebMethod
    @WebResult(targetNamespace = "http://www.openuri.org/jsr181/WebParamExample", partName = "return")
    public PingDocument echo(
        @WebParam(name = "arg0", partName = "arg0")
        PingDocument arg0);

}
