// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.userexceptioninheritance;


public class InheritedException extends org.jboss.test.webservice.userexceptioninheritance.CustomException {
    private java.lang.String additionalMessage;
    
    
    public InheritedException(java.lang.String message, int id, java.lang.String additionalMessage) {
        super(message, id);
        this.additionalMessage = additionalMessage;
    }
    
    public java.lang.String getAdditionalMessage() {
        return additionalMessage;
    }
}
