
package org.jboss.test.ws.jaxws.samples.retail.cc;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-10/21/2006 12:56 AM(vivek)-EA2
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "CCVerificationService", targetNamespace = "http://org.jboss.ws/samples/retail/cc", wsdlLocation = "resources/jaxws/samples/retail/META-INF/wsdl/CCVerificationService.wsdl")
public class CCVerificationService
    extends Service
{

    private final static URL CCVERIFICATIONSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/jaxws-samples-retail/CCVerificationBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        CCVERIFICATIONSERVICE_WSDL_LOCATION = url;
    }

    public CCVerificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CCVerificationService() {
        super(CCVERIFICATIONSERVICE_WSDL_LOCATION, new QName("http://org.jboss.ws/samples/retail/cc", "CCVerificationService"));
    }

    /**
     *
     * @return
     *     returns CCVerification
     */
    @WebEndpoint(name = "CCVerificationPort")
    public CCVerification getCCVerificationPort() {
        return (CCVerification)super.getPort(new QName("http://org.jboss.ws/samples/retail/cc", "CCVerificationPort"), CCVerification.class);
    }
}
