// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1184;


public class DataObject {
    protected java.lang.Boolean booleanValue;
    protected java.lang.Byte byteValue;
    protected java.lang.Float floatValue;
    protected java.lang.Integer integerValue;
    protected java.lang.Long longValue;
    protected java.lang.Short shortValue;
    
    public DataObject() {
    }
    
    public DataObject(java.lang.Boolean booleanValue, java.lang.Byte byteValue, java.lang.Float floatValue, java.lang.Integer integerValue, java.lang.Long longValue, java.lang.Short shortValue) {
        this.booleanValue = booleanValue;
        this.byteValue = byteValue;
        this.floatValue = floatValue;
        this.integerValue = integerValue;
        this.longValue = longValue;
        this.shortValue = shortValue;
    }
    
    public java.lang.Boolean getBooleanValue() {
        return booleanValue;
    }
    
    public void setBooleanValue(java.lang.Boolean booleanValue) {
        this.booleanValue = booleanValue;
    }
    
    public java.lang.Byte getByteValue() {
        return byteValue;
    }
    
    public void setByteValue(java.lang.Byte byteValue) {
        this.byteValue = byteValue;
    }
    
    public java.lang.Float getFloatValue() {
        return floatValue;
    }
    
    public void setFloatValue(java.lang.Float floatValue) {
        this.floatValue = floatValue;
    }
    
    public java.lang.Integer getIntegerValue() {
        return integerValue;
    }
    
    public void setIntegerValue(java.lang.Integer integerValue) {
        this.integerValue = integerValue;
    }
    
    public java.lang.Long getLongValue() {
        return longValue;
    }
    
    public void setLongValue(java.lang.Long longValue) {
        this.longValue = longValue;
    }
    
    public java.lang.Short getShortValue() {
        return shortValue;
    }
    
    public void setShortValue(java.lang.Short shortValue) {
        this.shortValue = shortValue;
    }
}
