// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetBoolResponse {
    protected java.lang.Boolean retBoolResult;
    
    public RetBoolResponse() {
    }
    
    public RetBoolResponse(java.lang.Boolean retBoolResult) {
        this.retBoolResult = retBoolResult;
    }
    
    public java.lang.Boolean getRetBoolResult() {
        return retBoolResult;
    }
    
    public void setRetBoolResult(java.lang.Boolean retBoolResult) {
        this.retBoolResult = retBoolResult;
    }
}
