// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetByteArray {
    protected byte[] inByteArray;
    
    public RetByteArray() {
    }
    
    public RetByteArray(byte[] inByteArray) {
        this.inByteArray = inByteArray;
    }
    
    public byte[] getInByteArray() {
        return inByteArray;
    }
    
    public void setInByteArray(byte[] inByteArray) {
        this.inByteArray = inByteArray;
    }
}
