// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetBool {
    protected java.lang.Boolean inBool;
    
    public RetBool() {
    }
    
    public RetBool(java.lang.Boolean inBool) {
        this.inBool = inBool;
    }
    
    public java.lang.Boolean getInBool() {
        return inBool;
    }
    
    public void setInBool(java.lang.Boolean inBool) {
        this.inBool = inBool;
    }
}
