// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetChar {
    protected java.lang.Integer inChar;
    
    public RetChar() {
    }
    
    public RetChar(java.lang.Integer inChar) {
        this.inChar = inChar;
    }
    
    public java.lang.Integer getInChar() {
        return inChar;
    }
    
    public void setInChar(java.lang.Integer inChar) {
        this.inChar = inChar;
    }
}
