// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetDoubleResponse {
    protected java.lang.Double retDoubleResult;
    
    public RetDoubleResponse() {
    }
    
    public RetDoubleResponse(java.lang.Double retDoubleResult) {
        this.retDoubleResult = retDoubleResult;
    }
    
    public java.lang.Double getRetDoubleResult() {
        return retDoubleResult;
    }
    
    public void setRetDoubleResult(java.lang.Double retDoubleResult) {
        this.retDoubleResult = retDoubleResult;
    }
}
