// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetDateTimeResponse {
    protected java.util.Calendar retDateTimeResult;
    
    public RetDateTimeResponse() {
    }
    
    public RetDateTimeResponse(java.util.Calendar retDateTimeResult) {
        this.retDateTimeResult = retDateTimeResult;
    }
    
    public java.util.Calendar getRetDateTimeResult() {
        return retDateTimeResult;
    }
    
    public void setRetDateTimeResult(java.util.Calendar retDateTimeResult) {
        this.retDateTimeResult = retDateTimeResult;
    }
}
