// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetDecimal {
    protected java.math.BigDecimal inDecimal;
    
    public RetDecimal() {
    }
    
    public RetDecimal(java.math.BigDecimal inDecimal) {
        this.inDecimal = inDecimal;
    }
    
    public java.math.BigDecimal getInDecimal() {
        return inDecimal;
    }
    
    public void setInDecimal(java.math.BigDecimal inDecimal) {
        this.inDecimal = inDecimal;
    }
}
