// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetFloat {
    protected java.lang.Float inFloat;
    
    public RetFloat() {
    }
    
    public RetFloat(java.lang.Float inFloat) {
        this.inFloat = inFloat;
    }
    
    public java.lang.Float getInFloat() {
        return inFloat;
    }
    
    public void setInFloat(java.lang.Float inFloat) {
        this.inFloat = inFloat;
    }
}
