// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetFloatResponse {
    protected java.lang.Float retFloatResult;
    
    public RetFloatResponse() {
    }
    
    public RetFloatResponse(java.lang.Float retFloatResult) {
        this.retFloatResult = retFloatResult;
    }
    
    public java.lang.Float getRetFloatResult() {
        return retFloatResult;
    }
    
    public void setRetFloatResult(java.lang.Float retFloatResult) {
        this.retFloatResult = retFloatResult;
    }
}
