// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetGuid {
    protected java.lang.String inGuid;
    
    public RetGuid() {
    }
    
    public RetGuid(java.lang.String inGuid) {
        this.inGuid = inGuid;
    }
    
    public java.lang.String getInGuid() {
        return inGuid;
    }
    
    public void setInGuid(java.lang.String inGuid) {
        this.inGuid = inGuid;
    }
}
