// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetInt {
    protected java.lang.Integer inInt;
    
    public RetInt() {
    }
    
    public RetInt(java.lang.Integer inInt) {
        this.inInt = inInt;
    }
    
    public java.lang.Integer getInInt() {
        return inInt;
    }
    
    public void setInInt(java.lang.Integer inInt) {
        this.inInt = inInt;
    }
}
