// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetIntResponse {
    protected java.lang.Integer retIntResult;
    
    public RetIntResponse() {
    }
    
    public RetIntResponse(java.lang.Integer retIntResult) {
        this.retIntResult = retIntResult;
    }
    
    public java.lang.Integer getRetIntResult() {
        return retIntResult;
    }
    
    public void setRetIntResult(java.lang.Integer retIntResult) {
        this.retIntResult = retIntResult;
    }
}
