// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetLong {
    protected java.lang.Long inLong;
    
    public RetLong() {
    }
    
    public RetLong(java.lang.Long inLong) {
        this.inLong = inLong;
    }
    
    public java.lang.Long getInLong() {
        return inLong;
    }
    
    public void setInLong(java.lang.Long inLong) {
        this.inLong = inLong;
    }
}
