// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetQName {
    protected javax.xml.namespace.QName inQName;
    
    public RetQName() {
    }
    
    public RetQName(javax.xml.namespace.QName inQName) {
        this.inQName = inQName;
    }
    
    public javax.xml.namespace.QName getInQName() {
        return inQName;
    }
    
    public void setInQName(javax.xml.namespace.QName inQName) {
        this.inQName = inQName;
    }
}
