// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetShortResponse {
    protected java.lang.Short retShortResult;
    
    public RetShortResponse() {
    }
    
    public RetShortResponse(java.lang.Short retShortResult) {
        this.retShortResult = retShortResult;
    }
    
    public java.lang.Short getRetShortResult() {
        return retShortResult;
    }
    
    public void setRetShortResult(java.lang.Short retShortResult) {
        this.retShortResult = retShortResult;
    }
}
