// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetSByteResponse {
    protected java.lang.Byte retSByteResult;
    
    public RetSByteResponse() {
    }
    
    public RetSByteResponse(java.lang.Byte retSByteResult) {
        this.retSByteResult = retSByteResult;
    }
    
    public java.lang.Byte getRetSByteResult() {
        return retSByteResult;
    }
    
    public void setRetSByteResult(java.lang.Byte retSByteResult) {
        this.retSByteResult = retSByteResult;
    }
}
