// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetTimeSpanResponse {
    protected java.lang.String retTimeSpanResult;
    
    public RetTimeSpanResponse() {
    }
    
    public RetTimeSpanResponse(java.lang.String retTimeSpanResult) {
        this.retTimeSpanResult = retTimeSpanResult;
    }
    
    public java.lang.String getRetTimeSpanResult() {
        return retTimeSpanResult;
    }
    
    public void setRetTimeSpanResult(java.lang.String retTimeSpanResult) {
        this.retTimeSpanResult = retTimeSpanResult;
    }
}
