// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetULong {
    protected java.math.BigInteger inULong;
    
    public RetULong() {
    }
    
    public RetULong(java.math.BigInteger inULong) {
        this.inULong = inULong;
    }
    
    public java.math.BigInteger getInULong() {
        return inULong;
    }
    
    public void setInULong(java.math.BigInteger inULong) {
        this.inULong = inULong;
    }
}
