// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetUIntResponse {
    protected long retUIntResult;
    
    public RetUIntResponse() {
    }
    
    public RetUIntResponse(long retUIntResult) {
        this.retUIntResult = retUIntResult;
    }
    
    public long getRetUIntResult() {
        return retUIntResult;
    }
    
    public void setRetUIntResult(long retUIntResult) {
        this.retUIntResult = retUIntResult;
    }
}
