// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW;


public class RetUShortResponse {
    protected int retUShortResult;
    
    public RetUShortResponse() {
    }
    
    public RetUShortResponse(int retUShortResult) {
        this.retUShortResult = retUShortResult;
    }
    
    public int getRetUShortResult() {
        return retUShortResult;
    }
    
    public void setRetUShortResult(int retUShortResult) {
        this.retUShortResult = retUShortResult;
    }
}
