
package org.jboss.test.ws.interop.wsse;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(
   name = "IPingService",
   targetNamespace = "http://InteropBaseAddress/interop"
)
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IPingService {

    @WebMethod(operationName = "Ping", action = "http://xmlsoap.org/Ping")
    public PingResponse ping(Ping request);

    /**
     * 
     * @param request
     * @return
     *     returns javax.xml.bind.JAXBElement<java.lang.String>
     */
    @WebMethod(action = "http://InteropBaseAddress/interop/echo")
    @WebResult(name = "echoResult", targetNamespace = "http://InteropBaseAddress/interop")
    public EchoResponse echo(Echo request);

}
