// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class LookupName {
    protected org.jboss.test.ws.jbws1260.Title[] surname;
    
    public LookupName() {
    }
    
    public LookupName(org.jboss.test.ws.jbws1260.Title[] surname) {
        this.surname = surname;
    }
    
    public org.jboss.test.ws.jbws1260.Title[] getSurname() {
        return surname;
    }
    
    public void setSurname(org.jboss.test.ws.jbws1260.Title[] surname) {
        this.surname = surname;
    }
}
