// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class Telephone {
    protected java.lang.String digits;
    
    public Telephone() {
    }
    
    public Telephone(java.lang.String digits) {
        this.digits = digits;
    }
    
    public java.lang.String getDigits() {
        return digits;
    }
    
    public void setDigits(java.lang.String digits) {
        this.digits = digits;
    }
}
