// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.attachment;

public interface Attachment_PortType extends java.rmi.Remote {
    public java.lang.String sendMimeImageGIF(java.lang.String message, java.awt.Image mimepart) throws 
         java.rmi.RemoteException;
    public java.lang.String sendMimeImageJPEG(java.lang.String message, java.awt.Image mimepart) throws 
         java.rmi.RemoteException;
    public java.lang.String sendMimeTextPlain(java.lang.String message, java.lang.String mimepart) throws 
         java.rmi.RemoteException;
    public java.lang.String sendMimeMultipart(java.lang.String message, javax.mail.internet.MimeMultipart mimepart) throws 
         java.rmi.RemoteException;
    public java.lang.String sendMimeTextXML(java.lang.String message, javax.xml.transform.Source mimepart) throws 
         java.rmi.RemoteException;
    public java.lang.String sendMimeApplicationXML(java.lang.String message, javax.xml.transform.Source mimepart) throws 
         java.rmi.RemoteException;
}
