<?xml version="1.0" encoding="UTF-8"?> 
<definitions name='MySEIService' targetNamespace='http://org.jboss.test.ws/jbws1217' xmlns='http://schemas.xmlsoap.org/wsdl/' xmlns:ns1='http://other.com' xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/' xmlns:tns='http://org.jboss.test.ws/jbws1217' xmlns:xsd='http://www.w3.org/2001/XMLSchema'> 
 <types> 
  <schema targetNamespace='http://other.com' xmlns='http://www.w3.org/2001/XMLSchema' xmlns:soap11-enc='http://schemas.xmlsoap.org/soap/encoding/' xmlns:tns='http://other.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'> 
   <complexType name='TestException'> 
    <sequence/> 
   </complexType> 
   <element name='TestException' type='tns:TestException'/> 
  </schema> 
 </types> 
 <message name='MySEI_testException'/> 
 <message name='MySEI_testExceptionResponse'/> 
 <message name='TestException'> 
  <part element='ns1:TestException' name='TestException'/> 
 </message> 
 <portType name='MySEI'> 
  <operation name='testException'> 
   <input message='tns:MySEI_testException'/> 
   <output message='tns:MySEI_testExceptionResponse'/> 
   <fault message='tns:TestException' name='TestException'/> 
  </operation> 
 </portType> 
 <binding name='MySEIBinding' type='tns:MySEI'> 
  <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http'/> 
  <operation name='testException'> 
   <soap:operation soapAction=''/> 
   <input> 
    <soap:body namespace='http://org.jboss.test.ws/jbws1217' use='literal'/> 
   </input> 
   <output> 
    <soap:body namespace='http://org.jboss.test.ws/jbws1217' use='literal'/> 
   </output> 
   <fault name='TestException'> 
    <soap:fault name='TestException' use='literal'/> 
   </fault> 
  </operation> 
 </binding> 
 <service name='MySEIService'> 
  <port binding='tns:MySEIBinding' name='MySEIPort'> 
   <soap:address location='REPLACE_WITH_ACTUAL_URL'/> 
  </port> 
 </service> 
</definitions>