/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jbws1217;


import javax.xml.rpc.*; 


public interface  MySEIService extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.jbws1217.MySEI getMySEIPort() throws ServiceException;

}
