// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitB_Service;

import javax.xml.rpc.*;

public interface BaseDataTypesDocLitBService extends javax.xml.rpc.Service {
    public org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitB_Service.IBaseDataTypesDocLitB getBasicHttpBinding_IBaseDataTypesDocLitB() throws ServiceException;
}
