// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class TelephoneNumber {
    protected java.lang.String[] number;
    
    public TelephoneNumber() {
    }
    
    public TelephoneNumber(java.lang.String[] number) {
        this.number = number;
    }
    
    public java.lang.String[] getNumber() {
        return number;
    }
    
    public void setNumber(java.lang.String[] number) {
        this.number = number;
    }
}
