// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class LookupName {
    protected java.lang.String postcode;
    
    public LookupName() {
    }
    
    public LookupName(java.lang.String postcode) {
        this.postcode = postcode;
    }
    
    public java.lang.String getPostcode() {
        return postcode;
    }
    
    public void setPostcode(java.lang.String postcode) {
        this.postcode = postcode;
    }
}
