// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws720;

import javax.xml.soap.Name;
import javax.xml.soap.SOAPElement;

public class GetProperty
{
   protected String strAttr;
   protected String lang;
   protected String strElement;
   protected SOAPElement[] _any;

   public GetProperty()
   {
   }

   public GetProperty(String strAttr, String lang, String strElement, SOAPElement[] _any)
   {
      this.strAttr = strAttr;
      this.lang = lang;
      this.strElement = strElement;
      this._any = _any;
   }

   public String getStrAttr()
   {
      return strAttr;
   }

   public void setStrAttr(String strAttr)
   {
      this.strAttr = strAttr;
   }

   public String getLang()
   {
      return lang;
   }

   public void setLang(String lang)
   {
      this.lang = lang;
   }

   public String getStrElement()
   {
      return strElement;
   }

   public void setStrElement(String strElement)
   {
      this.strElement = strElement;
   }

   public SOAPElement[] get_any()
   {
      return _any;
   }

   public void set_any(SOAPElement[] _any)
   {
      this._any = _any;
   }
   
   public boolean equals(Object obj)
   {
      if ((obj instanceof GetProperty) == false) return false;
      return toString().equals(obj.toString());
   }
   
   public String toString() 
   {
      StringBuffer builder = null;
      if (_any != null && _any.length > 0)
      {
         builder = new StringBuffer();
         for (int i =0; i < _any.length; i++)
         {
            SOAPElement sel = _any[i];
            Name name = sel.getElementName();
            builder.append(name);
         }
      }
      return "[elmt=" + strElement + ",attr=" + strAttr + ",lang=" + lang + ",any=" + builder + "]";
   }
}
