// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws720;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface TestEndpoint extends Remote
{
   public GetPropertyResponse getProperty(GetProperty parameters) throws RemoteException;
}
