// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class Country {
    protected java.lang.String name;
    protected javax.xml.soap.SOAPElement _any;

    public Country() {
    }

    public Country(java.lang.String name, javax.xml.soap.SOAPElement _any) {
        this.name = name;
        this._any = _any;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public javax.xml.soap.SOAPElement get_any() {
        return _any;
    }

    public void set_any(javax.xml.soap.SOAPElement _any) {
        this._any = _any;
    }
}