// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class USAddress {
    protected java.lang.String name;
    protected java.lang.String street;
    protected java.lang.String city;
    protected java.lang.String state;
    protected java.math.BigDecimal zip;

    public USAddress() {
    }

    public USAddress(java.lang.String name, java.lang.String street, java.lang.String city, java.lang.String state, java.math.BigDecimal zip) {
        this.name = name;
        this.street = street;
        this.city = city;
         this.state = state;
        this.zip = zip;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getStreet() {
        return street;
    }

    public void setStreet(java.lang.String street) {
        this.street = street;
    }

    public java.lang.String getCity() {
        return city;
 }

    public void setCity(java.lang.String city) {
        this.city = city;
    }

    public java.lang.String getState() {
        return state;
    }

    public void setState(java.lang.String state) {
        this.state = state;
    }

    public java.math.BigDecimal getZip() {
        return zip;
    }

    public void setZip(java.math.BigDecimal zip) {
        this.zip = zip;
    }
}
