<?xml version="1.0" encoding="UTF-8"?>
<definitions name="JBWS-2526"
             targetNamespace="urn:JBWS-2526-Service"
             xmlns:service="urn:JBWS-2526-Service"
             xmlns:schema="urn:JBWS-2526-Schema"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
             xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xs:schema>
      <xs:import namespace="urn:JBWS-2526-Schema"
                 schemaLocation="http://www.notexist.org/a.xsd"/>
    </xs:schema>
  </types>

  <message name="Request">
    <part name="request" element="schema:Request"/>
  </message>
  <message name="Response">
    <part name="response" element="schema:Response"/>
  </message>

  <portType name="Port">
    <operation name="evaluate">
      <input message="service:Request"/>
      <output message="service:Response"/>
    </operation>
  </portType>

  <binding name="Binding" type="service:Port">
    <soap:binding style="document"
                  transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="evaluate">
      <soap:operation/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>

  <service name="Service">
    <port binding="service:Binding" name="Port">
      <soap:address location="http://localhost:8080/jaxws-jbws2526"/>
    </port>
  </service>
</definitions>