<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="EndpointService" targetNamespace="http://org.jboss.ws/jbws1178" xmlns:ns1="http://schemas.xmlsoap.org/wsdl/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://org.jboss.ws/jbws1178" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:types>
   <xsd:schema>
      <xsd:import namespace="http://foo/bar" schemaLocation="schema1.xsd"/>
    </xsd:schema>
 </wsdl:types>
  <wsdl:message name="echoResponse">
    <wsdl:part name="return" type="xsd:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="echo">
    <wsdl:part name="arg0" type="xsd:string">
    </wsdl:part>
  </wsdl:message>

  <wsdl:portType name="Endpoint">
    <wsdl:operation name="echo">
      <wsdl:input message="tns:echo" name="echo">
    </wsdl:input>
      <wsdl:output message="tns:echoResponse" name="echoResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EndpointServiceSoapBinding" type="tns:Endpoint">

    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="echo">
      <soap:operation soapAction="" style="rpc" />
      <wsdl:input name="echo">
        <soap:body namespace="http://org.jboss.ws/jbws1178" use="literal" />
      </wsdl:input>
      <wsdl:output name="echoResponse">
        <soap:body namespace="http://org.jboss.ws/jbws1178" use="literal" />
      </wsdl:output>

    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="EndpointService">
    <wsdl:port binding="tns:EndpointServiceSoapBinding" name="EndpointPort">
      <soap:address location="http://blah/blah" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>