/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jbws1691;


import javax.xml.rpc.*; 


public interface  PhoneBookService extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.jbws1691.PhoneBook_PortType getPhoneBookPort() throws ServiceException;

}
