// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.usertypes;

public interface ComplexTypes extends java.rmi.Remote {
    public org.jboss.test.webservice.usertypes.Base echoBase(org.jboss.test.webservice.usertypes.Base base_1) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.usertypes.Composite echoCompositeType(org.jboss.test.webservice.usertypes.Composite composite_1) throws 
         java.rmi.RemoteException;
    public org.jboss.test.webservice.usertypes.Derived echoDerived(org.jboss.test.webservice.usertypes.Derived derived_1) throws 
         java.rmi.RemoteException;
}
