
package org.jboss.test.ws.jaxws.samples.webresult;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CustomerService", targetNamespace = "http://webresult.samples.jaxws.ws.test.jboss.org/", wsdlLocation = "META-INF/wsdl/CustomerService.wsdl")
@SOAPBinding(style = Style.RPC)
public interface CustomerService {


    /**
     * 
     * @param address
     * @param firstName
     * @param lastName
     * @return
     *     returns org.jboss.test.ws.jaxws.samples.webresult.CustomerRecord
     */
    @WebMethod
    @WebResult(name = "CustomerRecord", targetNamespace = "http://webresult.samples.jaxws.ws.test.jboss.org/", partName = "CustomerRecord")
    public CustomerRecord locateCustomer(
        @WebParam(name = "FirstName", partName = "FirstName")
        String firstName,
        @WebParam(name = "LastName", partName = "LastName")
        String lastName,
        @WebParam(name = "Address", partName = "Address")
        USAddress address);

}
