// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;

public interface PhoneBook_PortType extends java.rmi.Remote {
    public void lookup(org.jboss.test.ws.jbws1260.Person parameters, org.jboss.test.ws.jbws1260.Person anotherPerson, org.jboss.test.ws.jbws1260.holders.TelephoneNumberHolder result, org.jboss.test.ws.jbws1260.holders.TelephoneNumberHolder anotherTelephoneNumber) throws 
         java.rmi.RemoteException;
}
