// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class President {
    protected java.lang.String name;
    protected java.lang.String[] secretaries;
    protected int[] terms;

    public President() {
    }

    public President(java.lang.String name, java.lang.String[] secretaries, int[] terms) {
        this.name = name;
        this.secretaries = secretaries;
        this.terms = terms;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String[] getSecretaries() {
        return secretaries;
    }

    public void setSecretaries(java.lang.String[] secretaries) {
        this.secretaries = secretaries;
    }

    public int[] getTerms() {
        return terms;
    }

    public void setTerms(int[] terms) {
        this.terms = terms;
    }
}  