
package org.jboss.test.ws.jaxws.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import org.jboss.test.ws.jaxws.client.MTOMTest;
import org.jboss.test.ws.jaxws.client.MTOMTestService;
import org.jboss.test.ws.jaxws.client.MTOMTestTwo;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "MTOMTestService", targetNamespace = "http://mtomtestservice.org/wsdl", wsdlLocation = "./MTOMTestService.wsdl")
public class MTOMTestService
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName MTOMTESTSERVICE = new QName("http://mtomtestservice.org/wsdl", "MTOMTestService");
    private final static QName MTOMTESTPORT = new QName("http://mtomtestservice.org/wsdl", "MTOMTestPort");
    private final static QName MTOMTESTTWOPORT = new QName("http://mtomtestservice.org/wsdl", "MTOMTestTwoPort");

    static {
        URL url = null;
        try {
            url = new URL("file:/home/hbraun/dev/prj/jbossws/trunk/src/test/resources/jaxws/client/META-INF/MTOMTestService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MTOMTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTOMTestService() {
        super(WSDL_LOCATION, MTOMTESTSERVICE);
    }

    /**
     * 
     * @return
     *     returns MTOMTest
     */
    @WebEndpoint(name = "MTOMTestPort")
    public MTOMTest getMTOMTestPort() {
        return (MTOMTest)super.getPort(MTOMTESTPORT, MTOMTest.class);
    }

    /**
     * 
     * @return
     *     returns MTOMTestTwo
     */
    @WebEndpoint(name = "MTOMTestTwoPort")
    public MTOMTestTwo getMTOMTestTwoPort() {
        return (MTOMTestTwo)super.getPort(MTOMTESTTWOPORT, MTOMTestTwo.class);
    }

}
