
package org.jboss.test.ws.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import org.jboss.test.ws.jaxws.client.DataType3;
import org.jboss.test.ws.jaxws.client.MTOMTestTwo;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MTOMTestTwo", targetNamespace = "http://mtomtestservice.org/wsdl", wsdlLocation = "./MTOMTestService.wsdl")
public interface MTOMTestTwo {


    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MTOMIn2")
    @WebResult(name = "MTOMIn2Response", targetNamespace = "http://mtomtestservice.org/xsd", partName = "data")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    public String mtomIn2(
        @WebParam(name = "MTOMIn2", targetNamespace = "http://mtomtestservice.org/xsd", partName = "data")
        DataType3 data);

}
