
package org.jboss.test.ws.jaxws.client;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebParam.Mode;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.transform.Source;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.awt.*;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MTOMTest", targetNamespace = "http://mtomtestservice.org/wsdl", wsdlLocation = "./MTOMTestService.wsdl")
public interface MTOMTest {


    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MTOMIn")
    @WebResult(name = "MTOMInResponse", targetNamespace = "http://mtomtestservice.org/xsd", partName = "result")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    public String mtomIn(
        @WebParam(name = "MTOMIn", targetNamespace = "http://mtomtestservice.org/xsd", partName = "data")
        DataType data);

    /**
     * 
     * @param doc1
     * @param docName1
     * @param docUrl2
     * @param docName4
     * @param doc2
     * @param docUrl13
     * @param docName2
     * @param docUrl14
     * @param docUrl12
     * @param docName3
     * @param docUrl4
     * @param doc3
     * @param docUrl1
     * @param result
     * @param docUrl11
     * @param doc4
     * @param docUrl3
     */
    @WebMethod(operationName = "MTOMInOut")
    @RequestWrapper(localName = "MTOMInOut", targetNamespace = "http://mtomtestservice.org/xsd", className = "org.jboss.test.ws.jaxws.client.DataType2")
    @ResponseWrapper(localName = "MTOMInOutResponse", targetNamespace = "http://mtomtestservice.org/xsd", className = "org.jboss.test.ws.jaxws.client.DataType2")
    public void mtomInOut(
        @WebParam(name = "docName1", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docName1,
        @WebParam(name = "docName2", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docName2,
        @WebParam(name = "docName3", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docName3,
        @WebParam(name = "docName4", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docName4,
        @WebParam(name = "docUrl1", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl1,
        @WebParam(name = "docUrl2", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl2,
        @WebParam(name = "docUrl3", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl3,
        @WebParam(name = "docUrl4", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl4,
        @WebParam(name = "docUrl11", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl11,
        @WebParam(name = "docUrl12", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl12,
        @WebParam(name = "docUrl13", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl13,
        @WebParam(name = "docUrl14", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> docUrl14,
        @WebParam(name = "doc1", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<Source> doc1,
        @WebParam(name = "doc2", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<Source> doc2,
        @WebParam(name = "doc3", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<DataHandler> doc3,
        @WebParam(name = "doc4", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<Image> doc4,
        @WebParam(name = "result", targetNamespace = "http://mtomtestservice.org/xsd", mode = Mode.INOUT)
        Holder<String> result);

    /**
     * 
     * @param urls
     * @return
     *     returns org.jboss.test.ws.jaxws.client.DataType
     */
    @WebMethod(operationName = "MTOMOut")
    @WebResult(name = "MTOMOutResponse", targetNamespace = "http://mtomtestservice.org/xsd", partName = "data")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    public DataType mtomOut(
        @WebParam(name = "MTOMOut", targetNamespace = "http://mtomtestservice.org/xsd", partName = "urls")
        String urls);

    /**
     * 
     * @param urls
     * @return
     *     returns org.jboss.test.ws.jaxws.client.DataType3
     */
    @WebMethod(operationName = "MTOMOut2")
    @WebResult(name = "MTOMOut2Response", targetNamespace = "http://mtomtestservice.org/xsd", partName = "data")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    public DataType3 mtomOut2(
        @WebParam(name = "MTOMOut2", targetNamespace = "http://mtomtestservice.org/xsd", partName = "urls")
        String urls);

}
