// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TextTranslator_getQuotationStatus_ResponseStruct {
    protected org.jboss.test.ws.jaxrpc.jbws775.TQuoteStatus status;
    
    public TextTranslator_getQuotationStatus_ResponseStruct() {
    }
    
    public TextTranslator_getQuotationStatus_ResponseStruct(org.jboss.test.ws.jaxrpc.jbws775.TQuoteStatus status) {
        this.status = status;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws775.TQuoteStatus getStatus() {
        return status;
    }
    
    public void setStatus(org.jboss.test.ws.jaxrpc.jbws775.TQuoteStatus status) {
        this.status = status;
    }
}
