// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TextTranslator_getQuotationStatus_RequestStruct {
    protected java.lang.String clientName;
    
    public TextTranslator_getQuotationStatus_RequestStruct() {
    }
    
    public TextTranslator_getQuotationStatus_RequestStruct(java.lang.String clientName) {
        this.clientName = clientName;
    }
    
    public java.lang.String getClientName() {
        return clientName;
    }
    
    public void setClientName(java.lang.String clientName) {
        this.clientName = clientName;
    }
}
