// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TextTranslator_translate_ResponseStruct {
    protected java.lang.String translatedText;
    
    public TextTranslator_translate_ResponseStruct() {
    }
    
    public TextTranslator_translate_ResponseStruct(java.lang.String translatedText) {
        this.translatedText = translatedText;
    }
    
    public java.lang.String getTranslatedText() {
        return translatedText;
    }
    
    public void setTranslatedText(java.lang.String translatedText) {
        this.translatedText = translatedText;
    }
}
