// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TTextNotTranslatable extends java.lang.Exception {
    private java.lang.String text;
    
    
    public TTextNotTranslatable(java.lang.String text) {
        super(text);
        this.text = text;
    }
    
    public java.lang.String getText() {
        return text;
    }
}
