
package org.jboss.test.ws.jaxws.eardeployment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-11/15/2006 04:41 PM(vivek)-EA3
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "TestEndpointService", targetNamespace = "http://eardeployment.jaxws.ws.test.jboss.org/", wsdlLocation = "file:/home/tdiesler/svn/jbossws/trunk/src/test/resources/jaxws/eardeployment/META-INF/wsdl/TestEndpoint.wsdl")
public class TestEndpointService
    extends Service
{

    private final static URL TESTENDPOINTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/tdiesler/svn/jbossws/trunk/src/test/resources/jaxws/eardeployment/META-INF/wsdl/TestEndpoint.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TESTENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public TestEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestEndpointService() {
        super(TESTENDPOINTSERVICE_WSDL_LOCATION, new QName("http://eardeployment.jaxws.ws.test.jboss.org/", "TestEndpointService"));
    }

    /**
     * 
     * @return
     *     returns TestEndpoint
     */
    @WebEndpoint(name = "TestEndpointPort")
    public TestEndpoint getTestEndpointPort() {
        return (TestEndpoint)super.getPort(new QName("http://eardeployment.jaxws.ws.test.jboss.org/", "TestEndpointPort"), TestEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestEndpoint
     */
    @WebEndpoint(name = "TestEndpointPort")
    public TestEndpoint getTestEndpointPort(WebServiceFeature... features) {
        return (TestEndpoint)super.getPort(new QName("http://eardeployment.jaxws.ws.test.jboss.org/", "TestEndpointPort"), TestEndpoint.class, features);
    }

}
