/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.xop.rpclit;

import org.jboss.test.ws.jaxrpc.xop.shared.PingDataHandler;
import org.jboss.test.ws.jaxrpc.xop.shared.PingDataHandlerResponse;
import org.jboss.test.ws.jaxrpc.xop.shared.PingImage;
import org.jboss.test.ws.jaxrpc.xop.shared.PingImageResponse;
import org.jboss.test.ws.jaxrpc.xop.shared.PingSource;
import org.jboss.test.ws.jaxrpc.xop.shared.PingSourceResponse;

public interface XOPPing extends java.rmi.Remote
{
   public org.jboss.test.ws.jaxrpc.xop.shared.PingMsgResponse ping(org.jboss.test.ws.jaxrpc.xop.shared.PingMsg pingMsg) throws java.rmi.RemoteException;
   public byte[] pingSimple(String parameters, byte[] xopContent) throws java.rmi.RemoteException;
   public PingImageResponse pingImage(PingImage pingImage) throws java.rmi.RemoteException;
   public PingSourceResponse pingSource(PingSource pingSource) throws java.rmi.RemoteException;
   public PingDataHandlerResponse pingDataHandler(PingDataHandler pingDataHandler) throws java.rmi.RemoteException;
}
