//This class was generated by the JAXRPC SI, do not edit.
//Contents subject to change without notice.
//JAX-RPC Standard Implementation (1.1.2_01, build R40)
//Generated source version: 1.1.2

package org.jboss.types;

public interface HelloWs extends java.rmi.Remote {
 public java.lang.String sayHello(java.lang.String string_1) throws 
      java.rmi.RemoteException;
}