
package org.jboss.test.ws.interop.nov2007.wsse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PingService10", targetNamespace = "http://InteropBaseAddress/interop", wsdlLocation = "file:/home/alessio/Desktop/WS-Security%20interop%20files/wsdl_live_WsSecurity10.svc/WsSecurity10.wsdl")
public class PingService10
    extends Service
{

    private final static URL PINGSERVICE10_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/alessio/Desktop/WS-Security%20interop%20files/wsdl_live_WsSecurity10.svc/WsSecurity10.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PINGSERVICE10_WSDL_LOCATION = url;
    }

    public PingService10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService10() {
        super(PINGSERVICE10_WSDL_LOCATION, new QName("http://InteropBaseAddress/interop", "PingService10"));
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "UserNameOverTransport_IPingService")
    public IPingService getUserNameOverTransportIPingService() {
        return (IPingService)super.getPort(new QName("http://InteropBaseAddress/interop", "UserNameOverTransport_IPingService"), IPingService.class);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "MutualCertificate10SignEncrypt_IPingService")
    public IPingService getMutualCertificate10SignEncryptIPingService() {
        return (IPingService)super.getPort(new QName("http://InteropBaseAddress/interop", "MutualCertificate10SignEncrypt_IPingService"), IPingService.class);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "MutualCertificate10SignEncryptRsa15TripleDes_IPingService")
    public IPingService getMutualCertificate10SignEncryptRsa15TripleDesIPingService() {
        return (IPingService)super.getPort(new QName("http://InteropBaseAddress/interop", "MutualCertificate10SignEncryptRsa15TripleDes_IPingService"), IPingService.class);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "X10_IPingService")
    public IPingService getX10IPingService() {
        return (IPingService)super.getPort(new QName("http://InteropBaseAddress/interop", "X10_IPingService"), IPingService.class);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "X10-NoTimestamp_IPingService")
    public IPingService getX10NoTimestampIPingService() {
        return (IPingService)super.getPort(new QName("http://InteropBaseAddress/interop", "X10-NoTimestamp_IPingService"), IPingService.class);
    }

}
