// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.attachment;

import javax.xml.rpc.*;

public interface Attachment_Service extends javax.xml.rpc.Service {
    public org.jboss.test.webservice.attachment.Attachment_PortType getAttachmentPort() throws ServiceException;
}
