// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10;


public class Echo {
    protected java.lang.String request;
    
    public Echo() {
    }
    
    public Echo(java.lang.String request) {
        this.request = request;
    }
    
    public java.lang.String getRequest() {
        return request;
    }
    
    public void setRequest(java.lang.String request) {
        this.request = request;
    }
}
