// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10;

public interface IPingServiceSign extends java.rmi.Remote {
    public org.jboss.test.ws.interop.microsoft.security.wsse10.PingResponseBody ping(org.jboss.test.ws.interop.microsoft.security.wsse10.Ping ping) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.security.wsse10.EchoResponse echo(org.jboss.test.ws.interop.microsoft.security.wsse10.Echo parameters) throws 
         java.rmi.RemoteException;
}
