// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10;


public class PingResponseBody {
    protected java.lang.String scenario;
    protected java.lang.String origin;
    protected java.lang.String text;
    
    public PingResponseBody() {
    }
    
    public PingResponseBody(java.lang.String scenario, java.lang.String origin, java.lang.String text) {
        this.scenario = scenario;
        this.origin = origin;
        this.text = text;
    }
    
    public java.lang.String getScenario() {
        return scenario;
    }
    
    public void setScenario(java.lang.String scenario) {
        this.scenario = scenario;
    }
    
    public java.lang.String getOrigin() {
        return origin;
    }
    
    public void setOrigin(java.lang.String origin) {
        this.origin = origin;
    }
    
    public java.lang.String getText() {
        return text;
    }
    
    public void setText(java.lang.String text) {
        this.text = text;
    }
}
