// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10;

import javax.xml.rpc.*;

public interface PingService10Sign extends javax.xml.rpc.Service {
    public org.jboss.test.ws.interop.microsoft.security.wsse10.IPingServiceSign getMutualCertificate10Sign_IPingServiceSign() throws ServiceException;
}
