/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.samples.jsr109ejb;


public class  JaxRpcTestService_echoString_RequestStruct
{

protected java.lang.String String_1;

protected java.lang.String String_2;
public JaxRpcTestService_echoString_RequestStruct(){}

public JaxRpcTestService_echoString_RequestStruct(java.lang.String String_1,java.lang.String String_2){
this.String_1=String_1;
this.String_2=String_2;
}
public java.lang.String getString_1() { return String_1 ;}

public void setString_1(java.lang.String myvar ){  String_1=myvar ;}

public java.lang.String getString_2() { return String_2 ;}

public void setString_2(java.lang.String myvar ){  String_2=myvar ;}

}
