
package org.jboss.test.ws.jaxws.samples.webserviceref;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "SecureEndpointService", targetNamespace = "http://org.jboss.ws/wsref", wsdlLocation = "http://localhost.localdomain:8080/jaxws-samples-webserviceref-secure/SecureEndpoint?wsdl")
public class SecureEndpointService
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName SECUREENDPOINTSERVICE = new QName("http://org.jboss.ws/wsref", "SecureEndpointService");
    private final static QName SECUREENDPOINTPORT = new QName("http://org.jboss.ws/wsref", "SecureEndpointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost.localdomain:8080/jaxws-samples-webserviceref-secure/SecureEndpoint?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SecureEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecureEndpointService() {
        super(WSDL_LOCATION, SECUREENDPOINTSERVICE);
    }

    /**
     * 
     * @return
     *     returns SecureEndpoint
     */
    @WebEndpoint(name = "SecureEndpointPort")
    public SecureEndpoint getSecureEndpointPort() {
        return (SecureEndpoint)super.getPort(SECUREENDPOINTPORT, SecureEndpoint.class);
    }

}
