// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetBool_RequestStruct {
    protected boolean inBool;
    
    public IBaseDataTypesRpcLit_RetBool_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetBool_RequestStruct(boolean inBool) {
        this.inBool = inBool;
    }
    
    public boolean isInBool() {
        return inBool;
    }
    
    public void setInBool(boolean inBool) {
        this.inBool = inBool;
    }
}
