// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetLong_RequestStruct {
    protected long inLong;
    
    public IBaseDataTypesRpcLit_RetLong_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetLong_RequestStruct(long inLong) {
        this.inLong = inLong;
    }
    
    public long getInLong() {
        return inLong;
    }
    
    public void setInLong(long inLong) {
        this.inLong = inLong;
    }
}
