// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetString_RequestStruct {
    protected java.lang.String inString;
    
    public IBaseDataTypesRpcLit_RetString_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetString_RequestStruct(java.lang.String inString) {
        this.inString = inString;
    }
    
    public java.lang.String getInString() {
        return inString;
    }
    
    public void setInString(java.lang.String inString) {
        this.inString = inString;
    }
}
