// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetByteArray_ResponseStruct {
    protected byte[] retByteArrayResult;
    
    public IBaseDataTypesRpcLit_RetByteArray_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetByteArray_ResponseStruct(byte[] retByteArrayResult) {
        this.retByteArrayResult = retByteArrayResult;
    }
    
    public byte[] getRetByteArrayResult() {
        return retByteArrayResult;
    }
    
    public void setRetByteArrayResult(byte[] retByteArrayResult) {
        this.retByteArrayResult = retByteArrayResult;
    }
}
