// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetObject_RequestStruct {
    protected javax.xml.soap.SOAPElement inObject;
    
    public IBaseDataTypesRpcLit_RetObject_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetObject_RequestStruct(javax.xml.soap.SOAPElement inObject) {
        this.inObject = inObject;
    }
    
    public javax.xml.soap.SOAPElement getInObject() {
        return inObject;
    }
    
    public void setInObject(javax.xml.soap.SOAPElement inObject) {
        this.inObject = inObject;
    }
}
