// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetUShort_RequestStruct {
    protected int inUShort;
    
    public IBaseDataTypesRpcLit_RetUShort_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetUShort_RequestStruct(int inUShort) {
        this.inUShort = inUShort;
    }
    
    public int getInUShort() {
        return inUShort;
    }
    
    public void setInUShort(int inUShort) {
        this.inUShort = inUShort;
    }
}
