// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetChar_ResponseStruct {
    protected int retCharResult;
    
    public IBaseDataTypesRpcLit_RetChar_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetChar_ResponseStruct(int retCharResult) {
        this.retCharResult = retCharResult;
    }
    
    public int getRetCharResult() {
        return retCharResult;
    }
    
    public void setRetCharResult(int retCharResult) {
        this.retCharResult = retCharResult;
    }
}
