// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetDouble_RequestStruct {
    protected double inDouble;
    
    public IBaseDataTypesRpcLit_RetDouble_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetDouble_RequestStruct(double inDouble) {
        this.inDouble = inDouble;
    }
    
    public double getInDouble() {
        return inDouble;
    }
    
    public void setInDouble(double inDouble) {
        this.inDouble = inDouble;
    }
}
