// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetDecimal_RequestStruct {
    protected java.math.BigDecimal inDecimal;
    
    public IBaseDataTypesRpcLit_RetDecimal_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetDecimal_RequestStruct(java.math.BigDecimal inDecimal) {
        this.inDecimal = inDecimal;
    }
    
    public java.math.BigDecimal getInDecimal() {
        return inDecimal;
    }
    
    public void setInDecimal(java.math.BigDecimal inDecimal) {
        this.inDecimal = inDecimal;
    }
}
