// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetGuid_RequestStruct {
    protected java.lang.String inGuid;
    
    public IBaseDataTypesRpcLit_RetGuid_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetGuid_RequestStruct(java.lang.String inGuid) {
        this.inGuid = inGuid;
    }
    
    public java.lang.String getInGuid() {
        return inGuid;
    }
    
    public void setInGuid(java.lang.String inGuid) {
        this.inGuid = inGuid;
    }
}
