// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetInt_ResponseStruct {
    protected int retIntResult;
    
    public IBaseDataTypesRpcLit_RetInt_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetInt_ResponseStruct(int retIntResult) {
        this.retIntResult = retIntResult;
    }
    
    public int getRetIntResult() {
        return retIntResult;
    }
    
    public void setRetIntResult(int retIntResult) {
        this.retIntResult = retIntResult;
    }
}
