// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetInt_RequestStruct {
    protected int inInt;
    
    public IBaseDataTypesRpcLit_RetInt_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetInt_RequestStruct(int inInt) {
        this.inInt = inInt;
    }
    
    public int getInInt() {
        return inInt;
    }
    
    public void setInInt(int inInt) {
        this.inInt = inInt;
    }
}
