// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetSingle_ResponseStruct {
    protected float retSingleResult;
    
    public IBaseDataTypesRpcLit_RetSingle_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetSingle_ResponseStruct(float retSingleResult) {
        this.retSingleResult = retSingleResult;
    }
    
    public float getRetSingleResult() {
        return retSingleResult;
    }
    
    public void setRetSingleResult(float retSingleResult) {
        this.retSingleResult = retSingleResult;
    }
}
