// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetSingle_RequestStruct {
    protected float inSingle;
    
    public IBaseDataTypesRpcLit_RetSingle_RequestStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetSingle_RequestStruct(float inSingle) {
        this.inSingle = inSingle;
    }
    
    public float getInSingle() {
        return inSingle;
    }
    
    public void setInSingle(float inSingle) {
        this.inSingle = inSingle;
    }
}
