// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetBool_ResponseStruct {
    protected boolean retBoolResult;
    
    public IBaseDataTypesRpcLit_RetBool_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetBool_ResponseStruct(boolean retBoolResult) {
        this.retBoolResult = retBoolResult;
    }
    
    public boolean isRetBoolResult() {
        return retBoolResult;
    }
    
    public void setRetBoolResult(boolean retBoolResult) {
        this.retBoolResult = retBoolResult;
    }
}
