// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesRpcLit;


public class IBaseDataTypesRpcLit_RetShort_ResponseStruct {
    protected short retShortResult;
    
    public IBaseDataTypesRpcLit_RetShort_ResponseStruct() {
    }
    
    public IBaseDataTypesRpcLit_RetShort_ResponseStruct(short retShortResult) {
        this.retShortResult = retShortResult;
    }
    
    public short getRetShortResult() {
        return retShortResult;
    }
    
    public void setRetShortResult(short retShortResult) {
        this.retShortResult = retShortResult;
    }
}
