// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class LookupResponseNumber {
    protected java.lang.String areaCode;
    protected java.lang.String number;
    
    public LookupResponseNumber() {
    }
    
    public LookupResponseNumber(java.lang.String areaCode, java.lang.String number) {
        this.areaCode = areaCode;
        this.number = number;
    }
    
    public java.lang.String getAreaCode() {
        return areaCode;
    }
    
    public void setAreaCode(java.lang.String areaCode) {
        this.areaCode = areaCode;
    }
    
    public java.lang.String getNumber() {
        return number;
    }
    
    public void setNumber(java.lang.String number) {
        this.number = number;
    }
}
