// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfanyType {
    protected javax.xml.soap.SOAPElement[] anyType;
    
    public ArrayOfanyType() {
    }
    
    public ArrayOfanyType(javax.xml.soap.SOAPElement[] anyType) {
        this.anyType = anyType;
    }
    
    public javax.xml.soap.SOAPElement[] getAnyType() {
        return anyType;
    }
    
    public void setAnyType(javax.xml.soap.SOAPElement[] anyType) {
        this.anyType = anyType;
    }
}
