// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfint {
    protected int[] _int;
    
    public ArrayOfint() {
    }
    
    public ArrayOfint(int[] _int) {
        this._int = _int;
    }
    
    public int[] get_int() {
        return _int;
    }
    
    public void set_int(int[] _int) {
        this._int = _int;
    }
}
