// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfshort {
    protected short[] _short;
    
    public ArrayOfshort() {
    }
    
    public ArrayOfshort(short[] _short) {
        this._short = _short;
    }
    
    public short[] get_short() {
        return _short;
    }
    
    public void set_short(short[] _short) {
        this._short = _short;
    }
}
