// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfNullableOfdecimal {
    protected java.math.BigDecimal[] decimal;
    
    public ArrayOfNullableOfdecimal() {
    }
    
    public ArrayOfNullableOfdecimal(java.math.BigDecimal[] decimal) {
        this.decimal = decimal;
    }
    
    public java.math.BigDecimal[] getDecimal() {
        return decimal;
    }
    
    public void setDecimal(java.math.BigDecimal[] decimal) {
        this.decimal = decimal;
    }
}
