// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfPerson {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person[] person;
    
    public ArrayOfPerson() {
    }
    
    public ArrayOfPerson(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person[] person) {
        this.person = person;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person[] getPerson() {
        return person;
    }
    
    public void setPerson(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person[] person) {
        this.person = person;
    }
}
