// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfNullableOfdateTime {
    protected java.util.Calendar[] dateTime;
    
    public ArrayOfNullableOfdateTime() {
    }
    
    public ArrayOfNullableOfdateTime(java.util.Calendar[] dateTime) {
        this.dateTime = dateTime;
    }
    
    public java.util.Calendar[] getDateTime() {
        return dateTime;
    }
    
    public void setDateTime(java.util.Calendar[] dateTime) {
        this.dateTime = dateTime;
    }
}
