// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class ArrayOfArrayOfstring {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring[] arrayOfstring;
    
    public ArrayOfArrayOfstring() {
    }
    
    public ArrayOfArrayOfstring(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring[] arrayOfstring) {
        this.arrayOfstring = arrayOfstring;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring[] getArrayOfstring() {
        return arrayOfstring;
    }
    
    public void setArrayOfstring(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring[] arrayOfstring) {
        this.arrayOfstring = arrayOfstring;
    }
}
