// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;

import javax.xml.rpc.*;

public interface ComplexDataTypesRpcLitService extends javax.xml.rpc.Service {
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IComplexDataTypesRpcLit getBasicHttpBinding_IComplexDataTypesRpcLit() throws ServiceException;
}
