// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class Employee {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person baseDetails;
    protected java.util.Calendar hireDate;
    protected long jobID;
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort numbers;
    
    public Employee() {
    }
    
    public Employee(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person baseDetails, java.util.Calendar hireDate, long jobID, org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort numbers) {
        this.baseDetails = baseDetails;
        this.hireDate = hireDate;
        this.jobID = jobID;
        this.numbers = numbers;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person getBaseDetails() {
        return baseDetails;
    }
    
    public void setBaseDetails(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person baseDetails) {
        this.baseDetails = baseDetails;
    }
    
    public java.util.Calendar getHireDate() {
        return hireDate;
    }
    
    public void setHireDate(java.util.Calendar hireDate) {
        this.hireDate = hireDate;
    }
    
    public long getJobID() {
        return jobID;
    }
    
    public void setJobID(long jobID) {
        this.jobID = jobID;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort getNumbers() {
        return numbers;
    }
    
    public void setNumbers(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfshort numbers) {
        this.numbers = numbers;
    }
}
