// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class Furniture {
    protected java.lang.String color;
    protected java.lang.Float price;
    
    public Furniture() {
    }
    
    public Furniture(java.lang.String color, java.lang.Float price) {
        this.color = color;
        this.price = price;
    }
    
    public java.lang.String getColor() {
        return color;
    }
    
    public void setColor(java.lang.String color) {
        this.color = color;
    }
    
    public java.lang.Float getPrice() {
        return price;
    }
    
    public void setPrice(java.lang.Float price) {
        this.price = price;
    }
}
