// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayInt1D_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint retArrayInt1DResult;
    
    public IComplexDataTypesRpcLit_RetArrayInt1D_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayInt1D_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint retArrayInt1DResult) {
        this.retArrayInt1DResult = retArrayInt1DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint getRetArrayInt1DResult() {
        return retArrayInt1DResult;
    }
    
    public void setRetArrayInt1DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint retArrayInt1DResult) {
        this.retArrayInt1DResult = retArrayInt1DResult;
    }
}
