// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetEnumInt_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet inEnumInt;
    
    public IComplexDataTypesRpcLit_RetEnumInt_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetEnumInt_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet inEnumInt) {
        this.inEnumInt = inEnumInt;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet getInEnumInt() {
        return inEnumInt;
    }
    
    public void setInEnumInt(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet inEnumInt) {
        this.inEnumInt = inEnumInt;
    }
}
