// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetStructSNSA_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA;
    
    public IComplexDataTypesRpcLit_RetStructSNSA_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetStructSNSA_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA) {
        this.inStructSNSA = inStructSNSA;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee getInStructSNSA() {
        return inStructSNSA;
    }
    
    public void setInStructSNSA(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA) {
        this.inStructSNSA = inStructSNSA;
    }
}
