// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetStructS1_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name retStructS1Result;
    
    public IComplexDataTypesRpcLit_RetStructS1_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetStructS1_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name retStructS1Result) {
        this.retStructS1Result = retStructS1Result;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name getRetStructS1Result() {
        return retStructS1Result;
    }
    
    public void setRetStructS1Result(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name retStructS1Result) {
        this.retStructS1Result = retStructS1Result;
    }
}
