// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetStructSNSA_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee retStructSNSAResult;
    
    public IComplexDataTypesRpcLit_RetStructSNSA_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetStructSNSA_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee retStructSNSAResult) {
        this.retStructSNSAResult = retStructSNSAResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee getRetStructSNSAResult() {
        return retStructSNSAResult;
    }
    
    public void setRetStructSNSAResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee retStructSNSAResult) {
        this.retStructSNSAResult = retStructSNSAResult;
    }
}
