// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArray1D_SN_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson inArray1D_SN;
    
    public IComplexDataTypesRpcLit_RetArray1D_SN_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArray1D_SN_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson inArray1D_SN) {
        this.inArray1D_SN = inArray1D_SN;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson getInArray1D_SN() {
        return inArray1D_SN;
    }
    
    public void setInArray1D_SN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson inArray1D_SN) {
        this.inArray1D_SN = inArray1D_SN;
    }
}
