// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayString2D_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring retArrayString2DResult;
    
    public IComplexDataTypesRpcLit_RetArrayString2D_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayString2D_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring retArrayString2DResult) {
        this.retArrayString2DResult = retArrayString2DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring getRetArrayString2DResult() {
        return retArrayString2DResult;
    }
    
    public void setRetArrayString2DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfArrayOfstring retArrayString2DResult) {
        this.retArrayString2DResult = retArrayString2DResult;
    }
}
