// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayString1D_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring inArrayString1D;
    
    public IComplexDataTypesRpcLit_RetArrayString1D_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayString1D_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring inArrayString1D) {
        this.inArrayString1D = inArrayString1D;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring getInArrayString1D() {
        return inArrayString1D;
    }
    
    public void setInArrayString1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring inArrayString1D) {
        this.inArrayString1D = inArrayString1D;
    }
}
