// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetStructS1_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name inStructS1;
    
    public IComplexDataTypesRpcLit_RetStructS1_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetStructS1_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name inStructS1) {
        this.inStructS1 = inStructS1;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name getInStructS1() {
        return inStructS1;
    }
    
    public void setInStructS1(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Name inStructS1) {
        this.inStructS1 = inStructS1;
    }
}
