// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetDerivedClass_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table inDerivedClass;
    
    public IComplexDataTypesRpcLit_RetDerivedClass_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetDerivedClass_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table inDerivedClass) {
        this.inDerivedClass = inDerivedClass;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table getInDerivedClass() {
        return inDerivedClass;
    }
    
    public void setInDerivedClass(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table inDerivedClass) {
        this.inDerivedClass = inDerivedClass;
    }
}
