// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetStructSN_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person inStructSN;
    
    public IComplexDataTypesRpcLit_RetStructSN_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetStructSN_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person inStructSN) {
        this.inStructSN = inStructSN;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person getInStructSN() {
        return inStructSN;
    }
    
    public void setInStructSN(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person inStructSN) {
        this.inStructSN = inStructSN;
    }
}
