// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayDecimal1D_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal retArrayDecimal1DResult;
    
    public IComplexDataTypesRpcLit_RetArrayDecimal1D_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayDecimal1D_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal retArrayDecimal1DResult) {
        this.retArrayDecimal1DResult = retArrayDecimal1DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal getRetArrayDecimal1DResult() {
        return retArrayDecimal1DResult;
    }
    
    public void setRetArrayDecimal1DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal retArrayDecimal1DResult) {
        this.retArrayDecimal1DResult = retArrayDecimal1DResult;
    }
}
