// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayDateTime1D_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime inArrayDateTime1D;
    
    public IComplexDataTypesRpcLit_RetArrayDateTime1D_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayDateTime1D_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime inArrayDateTime1D) {
        this.inArrayDateTime1D = inArrayDateTime1D;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime getInArrayDateTime1D() {
        return inArrayDateTime1D;
    }
    
    public void setInArrayDateTime1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime inArrayDateTime1D) {
        this.inArrayDateTime1D = inArrayDateTime1D;
    }
}
