// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArray1D_SN_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson retArray1D_SNResult;
    
    public IComplexDataTypesRpcLit_RetArray1D_SN_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArray1D_SN_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson retArray1D_SNResult) {
        this.retArray1D_SNResult = retArray1D_SNResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson getRetArray1D_SNResult() {
        return retArray1D_SNResult;
    }
    
    public void setRetArray1D_SNResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfPerson retArray1D_SNResult) {
        this.retArray1D_SNResult = retArray1D_SNResult;
    }
}
