// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetEnumString_ResponseStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask retEnumStringResult;
    
    public IComplexDataTypesRpcLit_RetEnumString_ResponseStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetEnumString_ResponseStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask retEnumStringResult) {
        this.retEnumStringResult = retEnumStringResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask getRetEnumStringResult() {
        return retEnumStringResult;
    }
    
    public void setRetEnumStringResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask retEnumStringResult) {
        this.retEnumStringResult = retEnumStringResult;
    }
}
