// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class IComplexDataTypesRpcLit_RetArrayAnyType1D_RequestStruct {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType inArrayAnyType1D;
    
    public IComplexDataTypesRpcLit_RetArrayAnyType1D_RequestStruct() {
    }
    
    public IComplexDataTypesRpcLit_RetArrayAnyType1D_RequestStruct(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType inArrayAnyType1D) {
        this.inArrayAnyType1D = inArrayAnyType1D;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType getInArrayAnyType1D() {
        return inArrayAnyType1D;
    }
    
    public void setInArrayAnyType1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType inArrayAnyType1D) {
        this.inArrayAnyType1D = inArrayAnyType1D;
    }
}
