// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class Person {
    protected java.lang.Double age;
    protected java.lang.Float ID;
    protected java.lang.Boolean male;
    protected java.lang.String name;
    
    public Person() {
    }
    
    public Person(java.lang.Double age, java.lang.Float ID, java.lang.Boolean male, java.lang.String name) {
        this.age = age;
        this.ID = ID;
        this.male = male;
        this.name = name;
    }
    
    public java.lang.Double getAge() {
        return age;
    }
    
    public void setAge(java.lang.Double age) {
        this.age = age;
    }
    
    public java.lang.Float getID() {
        return ID;
    }
    
    public void setID(java.lang.Float ID) {
        this.ID = ID;
    }
    
    public java.lang.Boolean getMale() {
        return male;
    }
    
    public void setMale(java.lang.Boolean male) {
        this.male = male;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
