// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetArrayDateTime1DResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime retArrayDateTime1DResult;
    
    public RetArrayDateTime1DResponse() {
    }
    
    public RetArrayDateTime1DResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime retArrayDateTime1DResult) {
        this.retArrayDateTime1DResult = retArrayDateTime1DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime getRetArrayDateTime1DResult() {
        return retArrayDateTime1DResult;
    }
    
    public void setRetArrayDateTime1DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdateTime retArrayDateTime1DResult) {
        this.retArrayDateTime1DResult = retArrayDateTime1DResult;
    }
}
