// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetArrayDecimal1D {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal inArrayDecimal1D;
    
    public RetArrayDecimal1D() {
    }
    
    public RetArrayDecimal1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal inArrayDecimal1D) {
        this.inArrayDecimal1D = inArrayDecimal1D;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal getInArrayDecimal1D() {
        return inArrayDecimal1D;
    }
    
    public void setInArrayDecimal1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfNullableOfdecimal inArrayDecimal1D) {
        this.inArrayDecimal1D = inArrayDecimal1D;
    }
}
