// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetArrayString1DResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring retArrayString1DResult;
    
    public RetArrayString1DResponse() {
    }
    
    public RetArrayString1DResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring retArrayString1DResult) {
        this.retArrayString1DResult = retArrayString1DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring getRetArrayString1DResult() {
        return retArrayString1DResult;
    }
    
    public void setRetArrayString1DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfstring retArrayString1DResult) {
        this.retArrayString1DResult = retArrayString1DResult;
    }
}
