// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetArrayInt1D {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint inArrayInt1D;
    
    public RetArrayInt1D() {
    }
    
    public RetArrayInt1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint inArrayInt1D) {
        this.inArrayInt1D = inArrayInt1D;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint getInArrayInt1D() {
        return inArrayInt1D;
    }
    
    public void setInArrayInt1D(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfint inArrayInt1D) {
        this.inArrayInt1D = inArrayInt1D;
    }
}
