// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetArrayAnyType1DResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType retArrayAnyType1DResult;
    
    public RetArrayAnyType1DResponse() {
    }
    
    public RetArrayAnyType1DResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType retArrayAnyType1DResult) {
        this.retArrayAnyType1DResult = retArrayAnyType1DResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType getRetArrayAnyType1DResult() {
        return retArrayAnyType1DResult;
    }
    
    public void setRetArrayAnyType1DResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.ArrayOfanyType retArrayAnyType1DResult) {
        this.retArrayAnyType1DResult = retArrayAnyType1DResult;
    }
}
