// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetDerivedClassResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table retDerivedClassResult;
    
    public RetDerivedClassResponse() {
    }
    
    public RetDerivedClassResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table retDerivedClassResult) {
        this.retDerivedClassResult = retDerivedClassResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table getRetDerivedClassResult() {
        return retDerivedClassResult;
    }
    
    public void setRetDerivedClassResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Table retDerivedClassResult) {
        this.retDerivedClassResult = retDerivedClassResult;
    }
}
