// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetEnumString {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask inEnumString;
    
    public RetEnumString() {
    }
    
    public RetEnumString(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask inEnumString) {
        this.inEnumString = inEnumString;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask getInEnumString() {
        return inEnumString;
    }
    
    public void setInEnumString(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.BitMask inEnumString) {
        this.inEnumString = inEnumString;
    }
}
