// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetEnumIntResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet retEnumIntResult;
    
    public RetEnumIntResponse() {
    }
    
    public RetEnumIntResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet retEnumIntResult) {
        this.retEnumIntResult = retEnumIntResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet getRetEnumIntResult() {
        return retEnumIntResult;
    }
    
    public void setRetEnumIntResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.IntSet retEnumIntResult) {
        this.retEnumIntResult = retEnumIntResult;
    }
}
