// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetStructSNSAS {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group inStructSNSAS;
    
    public RetStructSNSAS() {
    }
    
    public RetStructSNSAS(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group inStructSNSAS) {
        this.inStructSNSAS = inStructSNSAS;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group getInStructSNSAS() {
        return inStructSNSAS;
    }
    
    public void setInStructSNSAS(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group inStructSNSAS) {
        this.inStructSNSAS = inStructSNSAS;
    }
}
