// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetStructSNSASResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group retStructSNSASResult;
    
    public RetStructSNSASResponse() {
    }
    
    public RetStructSNSASResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group retStructSNSASResult) {
        this.retStructSNSASResult = retStructSNSASResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group getRetStructSNSASResult() {
        return retStructSNSASResult;
    }
    
    public void setRetStructSNSASResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Group retStructSNSASResult) {
        this.retStructSNSASResult = retStructSNSASResult;
    }
}
