// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetStructSNResponse {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person retStructSNResult;
    
    public RetStructSNResponse() {
    }
    
    public RetStructSNResponse(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person retStructSNResult) {
        this.retStructSNResult = retStructSNResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person getRetStructSNResult() {
        return retStructSNResult;
    }
    
    public void setRetStructSNResult(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Person retStructSNResult) {
        this.retStructSNResult = retStructSNResult;
    }
}
