// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class RetStructSNSA {
    protected org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA;
    
    public RetStructSNSA() {
    }
    
    public RetStructSNSA(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA) {
        this.inStructSNSA = inStructSNSA;
    }
    
    public org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee getInStructSNSA() {
        return inStructSNSA;
    }
    
    public void setInStructSNSA(org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Employee inStructSNSA) {
        this.inStructSNSA = inStructSNSA;
    }
}
