// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared;


public class Table extends org.jboss.test.ws.interop.microsoft.soapwsdl.ComplexDataTypesShared.Furniture {
    protected java.lang.Integer seatingCapacity;
    
    public Table() {
    }
    
    public Table(java.lang.String color, java.lang.Float price, java.lang.Integer seatingCapacity) {
        this.color = color;
        this.price = price;
        this.seatingCapacity = seatingCapacity;
    }
    
    public java.lang.Integer getSeatingCapacity() {
        return seatingCapacity;
    }
    
    public void setSeatingCapacity(java.lang.Integer seatingCapacity) {
        this.seatingCapacity = seatingCapacity;
    }
}
