/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.jbws732;


import javax.xml.rpc.ServiceException;


public interface  BareService extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.jaxrpc.jbws732.BareEndpoint getBareEndpointPort() throws ServiceException;

}
