// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1450;

public interface TestEndpoint_PortType extends java.rmi.Remote {
    public boolean testBoolean(boolean boolean_1) throws 
         java.rmi.RemoteException;
    public byte testByte(byte byte_1) throws 
         java.rmi.RemoteException;
    public float testFloat(float float_1) throws 
         java.rmi.RemoteException;
    public int testInteger(int integer_1) throws 
         java.rmi.RemoteException;
    public long testLong(long long_1) throws 
         java.rmi.RemoteException;
    public short testShort(short short_1) throws 
         java.rmi.RemoteException;
}
