// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.usertypes;


public class Composite {
    protected org.jboss.test.webservice.usertypes.Composite composite;
    protected java.util.Calendar dateTime;
    protected java.math.BigInteger integer;
    protected javax.xml.namespace.QName qname;
    protected java.lang.String string;
    
    public Composite() {
    }
    
    public Composite(org.jboss.test.webservice.usertypes.Composite composite, java.util.Calendar dateTime, java.math.BigInteger integer, javax.xml.namespace.QName qname, java.lang.String string) {
        this.composite = composite;
        this.dateTime = dateTime;
        this.integer = integer;
        this.qname = qname;
        this.string = string;
    }
    
    public org.jboss.test.webservice.usertypes.Composite getComposite() {
        return composite;
    }
    
    public void setComposite(org.jboss.test.webservice.usertypes.Composite composite) {
        this.composite = composite;
    }
    
    public java.util.Calendar getDateTime() {
        return dateTime;
    }
    
    public void setDateTime(java.util.Calendar dateTime) {
        this.dateTime = dateTime;
    }
    
    public java.math.BigInteger getInteger() {
        return integer;
    }
    
    public void setInteger(java.math.BigInteger integer) {
        this.integer = integer;
    }
    
    public javax.xml.namespace.QName getQname() {
        return qname;
    }
    
    public void setQname(javax.xml.namespace.QName qname) {
        this.qname = qname;
    }
    
    public java.lang.String getString() {
        return string;
    }
    
    public void setString(java.lang.String string) {
        this.string = string;
    }
}
