// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.usertypes;


public class Derived extends org.jboss.test.webservice.usertypes.Base {
    protected int x;
    
    public Derived() {
    }
    
    public Derived(int a, int b, int x) {
        this.a = a;
        this.b = b;
        this.x = x;
    }
    
    public int getX() {
        return x;
    }
    
    public void setX(int x) {
        this.x = x;
    }
}
