// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1259;


public class Comment {
    protected java.lang.String test;
    protected org.jboss.test.ws.jbws1259.Comment comment;
    
    public Comment() {
    }
    
    public Comment(java.lang.String test, org.jboss.test.ws.jbws1259.Comment comment) {
        this.test = test;
        this.comment = comment;
    }
    
    public java.lang.String getTest() {
        return test;
    }
    
    public void setTest(java.lang.String test) {
        this.test = test;
    }
    
    public org.jboss.test.ws.jbws1259.Comment getComment() {
        return comment;
    }
    
    public void setComment(org.jboss.test.ws.jbws1259.Comment comment) {
        this.comment = comment;
    }
}
