
package org.jboss.test.ws.jaxws.samples.retail.profile;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-10/21/2006 12:56 AM(vivek)-EA2
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "ProfileMgmtService", targetNamespace = "http://org.jboss.ws/samples/retail/profile", wsdlLocation = "resources/jaxws/samples/retail/META-INF/wsdl/ProfileMgmtService.wsdl")
public class ProfileMgmtService
    extends Service
{

    private final static URL PROFILEMGMTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/jaxws-samples-retail/ProfileMgmtBean?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        PROFILEMGMTSERVICE_WSDL_LOCATION = url;
    }

    public ProfileMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfileMgmtService() {
        super(PROFILEMGMTSERVICE_WSDL_LOCATION, new QName("http://org.jboss.ws/samples/retail/profile", "ProfileMgmtService"));
    }

    /**
     *
     * @return
     *     returns ProfileMgmt
     */
    @WebEndpoint(name = "ProfileMgmtPort")
    public ProfileMgmt getProfileMgmtPort() {
        return (ProfileMgmt)super.getPort(new QName("http://org.jboss.ws/samples/retail/profile", "ProfileMgmtPort"), ProfileMgmt.class);
    }
}
