// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.ws.jaxrpc.encoded.parametermode.holders;


import javax.xml.rpc.holders.Holder;

public class EnumIntHolder implements Holder {
    public org.jboss.test.ws.jaxrpc.encoded.parametermode.EnumInt value;
    
    public EnumIntHolder() {
    }
    
    public EnumIntHolder(org.jboss.test.ws.jaxrpc.encoded.parametermode.EnumInt myEnumInt) {
        this.value = myEnumInt;
    }
}
