// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test;

public interface HelloCustomRemote extends java.rmi.Remote {
    public org.jboss.test.HelloObjArray helloArray(org.jboss.test.HelloObjArray
arrayOfHelloObj_1) throws
         java.rmi.RemoteException;
    public org.jboss.test.HelloObj helloBean(org.jboss.test.HelloObj helloObj_1)
 throws
         java.rmi.RemoteException;
    public java.lang.String helloString(java.lang.String string_1) throws
         java.rmi.RemoteException;
}