/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.samples.jsr109pojo;


public class  JaxRpcTestService_echoSimpleUserType_ResponseStruct
{

protected org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType result;
public JaxRpcTestService_echoSimpleUserType_ResponseStruct(){}

public JaxRpcTestService_echoSimpleUserType_ResponseStruct(org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType result){
this.result=result;
}
public org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType getResult() { return result ;}

public void setResult(org.jboss.test.ws.jaxrpc.samples.jsr109pojo.SimpleUserType myvar ){  result=myvar ;}

}
