/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.samples.jsr109pojo;


public class  JaxRpcTestService_echoString_ResponseStruct
{

protected java.lang.String result;
public JaxRpcTestService_echoString_ResponseStruct(){}

public JaxRpcTestService_echoString_ResponseStruct(java.lang.String result){
this.result=result;
}
public java.lang.String getResult() { return result ;}

public void setResult(java.lang.String myvar ){  result=myvar ;}

}
