// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.test.ws.jaxrpc.encoded.parametermode;

public class Book
{
   protected java.lang.String author;
   protected java.lang.String title;
   protected int isbn;

   public Book()
   {
   }

   public Book(java.lang.String author, java.lang.String title, int isbn)
   {
      this.author = author;
      this.title = title;
      this.isbn = isbn;
   }

   public java.lang.String getAuthor()
   {
      return author;
   }

   public void setAuthor(java.lang.String author)
   {
      this.author = author;
   }

   public java.lang.String getTitle()
   {
      return title;
   }

   public void setTitle(java.lang.String title)
   {
      this.title = title;
   }

   public int getIsbn()
   {
      return isbn;
   }

   public void setIsbn(int isbn)
   {
      this.isbn = isbn;
   }

   public boolean equals(Object obj)
   {
      if (obj == null) return false;
      return toString().equals(obj.toString());
   }
   
   public String toString()
   {
      return "[author=" + author + ",title=" + title + ",isbn=" + isbn + "]";
   }
}
