
package org.jboss.test.ws.jaxws.jbws1857.types;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "StammdatenService", targetNamespace = "http://example.com", wsdlLocation = "file:/home/tdiesler/svn/jbossws/stack/native/trunk/src/test/resources/jaxws/jbws1857/StammdatenService.wsdl")
public class StammdatenService
    extends Service
{

    private final static URL STAMMDATENSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/home/tdiesler/svn/jbossws/stack/native/trunk/src/test/resources/jaxws/jbws1857/StammdatenService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        STAMMDATENSERVICE_WSDL_LOCATION = url;
    }

    public StammdatenService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StammdatenService() {
        super(STAMMDATENSERVICE_WSDL_LOCATION, new QName("http://example.com", "StammdatenService"));
    }

    /**
     * 
     * @return
     *     returns Stammdaten
     */
    @WebEndpoint(name = "StammdatenPort")
    public Stammdaten getStammdatenPort() {
        return (Stammdaten)super.getPort(new QName("http://example.com", "StammdatenPort"), Stammdaten.class);
    }

}
