// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;

import java.rmi.Remote;
import java.rmi.RemoteException;

public interface DocumentTranslator extends Remote
{
   public TDocument translate(TTranslationRequest translationRequest) throws TTextNotTranslatable, TDictionaryNotAvailable, RemoteException;

   public void quoteTranslation(TQuotationRequest quotationRequest) throws RemoteException;

   public TStatusResponse getQuotationStatus(TStatusRequest statusRequest) throws RemoteException;
}
