// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;


public class TDocument {
    protected org.jboss.test.ws.jaxrpc.jbws775.TDocumentHead head;
    protected org.jboss.test.ws.jaxrpc.jbws775.TDocumentBody body;
    
    public TDocument() {
    }
    
    public TDocument(org.jboss.test.ws.jaxrpc.jbws775.TDocumentHead head, org.jboss.test.ws.jaxrpc.jbws775.TDocumentBody body) {
        this.head = head;
        this.body = body;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws775.TDocumentHead getHead() {
        return head;
    }
    
    public void setHead(org.jboss.test.ws.jaxrpc.jbws775.TDocumentHead head) {
        this.head = head;
    }
    
    public org.jboss.test.ws.jaxrpc.jbws775.TDocumentBody getBody() {
        return body;
    }
    
    public void setBody(org.jboss.test.ws.jaxrpc.jbws775.TDocumentBody body) {
        this.body = body;
    }
}
