// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.jbws775;

import javax.xml.rpc.ServiceException;

public interface TranslatorService extends javax.xml.rpc.Service {
    public TextTranslator getTextTranslatorPort() throws ServiceException;
    public DocumentTranslator getDocumentTranslatorPort() throws ServiceException;
}
