// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1450;

public interface TestEndpoint_PortType extends java.rmi.Remote {
    public java.lang.Boolean testBoolean(java.lang.Boolean boolean_1) throws 
         java.rmi.RemoteException;
    public java.lang.Byte testByte(java.lang.Byte byte_1) throws 
         java.rmi.RemoteException;
    public java.lang.Float testFloat(java.lang.Float float_1) throws 
         java.rmi.RemoteException;
    public java.lang.Integer testInteger(java.lang.Integer integer_1) throws 
         java.rmi.RemoteException;
    public java.lang.Long testLong(java.lang.Long long_1) throws 
         java.rmi.RemoteException;
    public java.lang.Short testShort(java.lang.Short short_1) throws 
         java.rmi.RemoteException;
}
