// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1079;

public interface PhoneBook_PortType extends java.rmi.Remote {
    public org.jboss.test.ws.jbws1079.TelephoneNumber lookup(org.jboss.test.ws.jbws1079.Person parameters) throws 
         java.rmi.RemoteException;
}
