// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1079;


public class TelephoneNumber {
    protected org.jboss.test.ws.jbws1079.LookupResponseNumber number;
    
    public TelephoneNumber() {
    }
    
    public TelephoneNumber(org.jboss.test.ws.jbws1079.LookupResponseNumber number) {
        this.number = number;
    }
    
    public org.jboss.test.ws.jbws1079.LookupResponseNumber getNumber() {
        return number;
    }
    
    public void setNumber(org.jboss.test.ws.jbws1079.LookupResponseNumber number) {
        this.number = number;
    }
}
