/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org.
 */

//Auto Generated by jbossws - Please do not edit!!!
package org.jboss.test.ws.jaxws.jbws871;

import javax.xml.rpc.Service;
import javax.xml.rpc.ServiceException;

public interface RpcArrayEndpointService extends Service
{
   public RpcArrayEndpoint getRpcArrayEndpointPort() throws ServiceException;

}
