
package org.jboss.test.ws.jaxws.samples.jsr181ejb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-11/15/2006 04:41 PM(vivek)-EA3
 * Generated source version: 2.1
 * 
 */
@WebService(name = "EndpointInterface", targetNamespace = "http://org.jboss.ws/samples/jsr181ejb")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface EndpointInterface {


    /**
     * 
     * @param string1
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "result", partName = "result")
    public String echo(
        @WebParam(name = "String_1", partName = "String_1")
        String string1);

}
