// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.addressing.wsaTestService;

public interface WsaTestPortType extends java.rmi.Remote {
    public void notify(java.lang.String wsaNotifyMessagePart) throws 
         java.rmi.RemoteException;
    public java.lang.String echo(java.lang.String wsaEchoInPart) throws 
         java.rmi.RemoteException;
    public void echoOut(java.lang.String wsaEchoOutPart) throws 
         java.rmi.RemoteException;
}
