/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.xop.shared;

public class PingMsg
{
   protected String message;
   protected byte[] xopContent;

   public PingMsg(){}

   public PingMsg(String message, byte[] dataHandler){
      this.message=message;
      this.xopContent = dataHandler;
   }

   public java.lang.String getMessage() { return message ;}

   public void setMessage(java.lang.String message){ this.message=message; }

   public byte[] getXopContent() {
      return xopContent;
   }

   public void setXopContent(byte[] xopContent) {
      this.xopContent = xopContent;
   }
}
