/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.xop.doclit;

import org.jboss.test.ws.jaxrpc.xop.shared.*;

public interface XOPPing extends java.rmi.Remote
{
   public PingMsgResponse ping(PingMsg pingMsg) throws java.rmi.RemoteException;
   public PingImageResponse pingImage(PingImage pingImage) throws java.rmi.RemoteException;
   public PingSourceResponse pingSource(PingSource pingSource) throws java.rmi.RemoteException;
   public PingDataHandlerResponse pingDataHandler(PingDataHandler pingDataHandler) throws java.rmi.RemoteException;
}
