/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.webserviceref;


import javax.xml.rpc.*; 


public interface  TestEndpointService extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.jaxrpc.webserviceref.TestEndpoint getTestEndpointPort() throws ServiceException;

}
