
package org.jboss.test.ws.interop.wsse;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0-b26-ea3
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "PingService10", targetNamespace = "http://tempuri.org/", wsdlLocation = "WEB-INF/wsdl/WsSecurity10.wsdl")
public class PingService10
    extends Service
{

    private final static URL WSDL_LOCATION;
    private final static QName PINGSERVICE10 = new QName("http://tempuri.org/", "PingService10");
    private final static QName MUTUALCERTIFICATE10IPINGSERVICE = new QName("http://tempuri.org/", "MutualCertificate10_IPingService");

    static {
        URL url = null;
        try {
            url = new URL("file:/home/hbraun/dev/prj/jbossws/trunk/jbossws-tests/src/main/resources/interop/wsse/shared/WEB-INF/wsdl/WsSecurity10.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public PingService10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PingService10() {
        super(WSDL_LOCATION, PINGSERVICE10);
    }

    /**
     * 
     * @return
     *     returns IPingService
     */
    @WebEndpoint(name = "MutualCertificate10_IPingService")
    public IPingService getMutualCertificate10IPingService() {
        return (IPingService)super.getPort(MUTUALCERTIFICATE10IPINGSERVICE, IPingService.class);
    }

}
