// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class Address {
    protected java.lang.String city;
    protected java.lang.String state;
    protected java.lang.String street;
    protected java.lang.String zip;
    
    public Address() {
    }
    
    public Address(java.lang.String city, java.lang.String state, java.lang.String street, java.lang.String zip) {
        this.city = city;
        this.state = state;
        this.street = street;
        this.zip = zip;
    }
    
    public java.lang.String getCity() {
        return city;
    }
    
    public void setCity(java.lang.String city) {
        this.city = city;
    }
    
    public java.lang.String getState() {
        return state;
    }
    
    public void setState(java.lang.String state) {
        this.state = state;
    }
    
    public java.lang.String getStreet() {
        return street;
    }
    
    public void setStreet(java.lang.String street) {
        this.street = street;
    }
    
    public java.lang.String getZip() {
        return zip;
    }
    
    public void setZip(java.lang.String zip) {
        this.zip = zip;
    }
}
