// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class AlreadyRegisteredException extends org.jboss.test.ws.jaxws.jsr181.complex.client.RegistrationException {
    private long existingId;
    
    
    public AlreadyRegisteredException(java.lang.String message, long existingId) {
        super(message);
        this.existingId = existingId;
    }
    
    public long getExistingId() {
        return existingId;
    }
}
