// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class BulkRegisterResponse {
    protected long[] registeredIDs;
    
    public BulkRegisterResponse() {
    }
    
    public BulkRegisterResponse(long[] registeredIDs) {
        this.registeredIDs = registeredIDs;
    }
    
    public long[] getRegisteredIDs() {
        return registeredIDs;
    }
    
    public void setRegisteredIDs(long[] registeredIDs) {
        this.registeredIDs = registeredIDs;
    }
}
