// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class BulkRegister {
    protected org.jboss.test.ws.jaxws.jsr181.complex.client.Customer[] customers;
    protected java.util.Calendar when;
    
    public BulkRegister() {
    }
    
    public BulkRegister(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer[] customers, java.util.Calendar when) {
        this.customers = customers;
        this.when = when;
    }
    
    public org.jboss.test.ws.jaxws.jsr181.complex.client.Customer[] getCustomers() {
        return customers;
    }
    
    public void setCustomers(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer[] customers) {
        this.customers = customers;
    }
    
    public java.util.Calendar getWhen() {
        return when;
    }
    
    public void setWhen(java.util.Calendar when) {
        this.when = when;
    }
}
