// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class Customer {
    protected Address address;
    protected PhoneNumber[] contactNumbers;
    protected long id;
    protected Name name;

    // since there is no way to differentiate between a null array
    // and an array with 1 element that is null
    protected Customer[] referredCustomers = new Customer[0];

    public Customer() {
    }

    public Customer(Address address, PhoneNumber[] contactNumbers, long id, Name name, Customer[] referredCustomers) {
        this.address = address;
        this.contactNumbers = contactNumbers;
        this.id = id;
        this.name = name;
        this.referredCustomers = referredCustomers;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }

    public PhoneNumber[] getContactNumbers() {
        return contactNumbers;
    }

    public void setContactNumbers(PhoneNumber[] contactNumbers) {
        this.contactNumbers = contactNumbers;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public Name getName() {
        return name;
    }

    public void setName(Name name) {
        this.name = name;
    }

    public Customer[] getReferredCustomers() {
        return referredCustomers;
    }

    public void setReferredCustomers(Customer[] referredCustomers) {
        this.referredCustomers = referredCustomers;
    }
}
