// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class GetStatistics {
    protected org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer;
    
    public GetStatistics() {
    }
    
    public GetStatistics(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer) {
        this.customer = customer;
    }
    
    public org.jboss.test.ws.jaxws.jsr181.complex.client.Customer getCustomer() {
        return customer;
    }
    
    public void setCustomer(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer) {
        this.customer = customer;
    }
}
