// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class GetStatisticsResponse {
    protected org.jboss.test.ws.jaxws.jsr181.complex.client.Statistics statistics;
    
    public GetStatisticsResponse() {
    }
    
    public GetStatisticsResponse(org.jboss.test.ws.jaxws.jsr181.complex.client.Statistics statistics) {
        this.statistics = statistics;
    }
    
    public org.jboss.test.ws.jaxws.jsr181.complex.client.Statistics getStatistics() {
        return statistics;
    }
    
    public void setStatistics(org.jboss.test.ws.jaxws.jsr181.complex.client.Statistics statistics) {
        this.statistics = statistics;
    }
}
