// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class InvoiceCustomer extends org.jboss.test.ws.jaxws.jsr181.complex.client.Customer {
    protected int cycleDay;
    
    public InvoiceCustomer() {
    }
    
    public InvoiceCustomer(org.jboss.test.ws.jaxws.jsr181.complex.client.Address address, org.jboss.test.ws.jaxws.jsr181.complex.client.PhoneNumber[] contactNumbers, long id, org.jboss.test.ws.jaxws.jsr181.complex.client.Name name, org.jboss.test.ws.jaxws.jsr181.complex.client.Customer[] referredCustomers, int cycleDay) {
        this.address = address;
        this.contactNumbers = contactNumbers;
        this.id = id;
        this.name = name;
        this.referredCustomers = referredCustomers;
        this.cycleDay = cycleDay;
    }
    
    public int getCycleDay() {
        return cycleDay;
    }
    
    public void setCycleDay(int cycleDay) {
        this.cycleDay = cycleDay;
    }
}
