// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class Name {
    protected java.lang.String firstName;
    protected java.lang.String lastName;
    protected java.lang.String middleName;
    
    public Name() {
    }
    
    public Name(java.lang.String firstName, java.lang.String lastName, java.lang.String middleName) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.middleName = middleName;
    }
    
    public java.lang.String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }
    
    public java.lang.String getLastName() {
        return lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }
    
    public java.lang.String getMiddleName() {
        return middleName;
    }
    
    public void setMiddleName(java.lang.String middleName) {
        this.middleName = middleName;
    }
}
