// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class PhoneNumber {
    protected java.lang.String areaCode;
    protected java.lang.String exchange;
    protected java.lang.String line;
    
    public PhoneNumber() {
    }
    
    public PhoneNumber(java.lang.String areaCode, java.lang.String exchange, java.lang.String line) {
        this.areaCode = areaCode;
        this.exchange = exchange;
        this.line = line;
    }
    
    public java.lang.String getAreaCode() {
        return areaCode;
    }
    
    public void setAreaCode(java.lang.String areaCode) {
        this.areaCode = areaCode;
    }
    
    public java.lang.String getExchange() {
        return exchange;
    }
    
    public void setExchange(java.lang.String exchange) {
        this.exchange = exchange;
    }
    
    public java.lang.String getLine() {
        return line;
    }
    
    public void setLine(java.lang.String line) {
        this.line = line;
    }
}
