// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class RegisterForInvoice {
    protected org.jboss.test.ws.jaxws.jsr181.complex.client.InvoiceCustomer invoiceCustomer;
    
    public RegisterForInvoice() {
    }
    
    public RegisterForInvoice(org.jboss.test.ws.jaxws.jsr181.complex.client.InvoiceCustomer invoiceCustomer) {
        this.invoiceCustomer = invoiceCustomer;
    }
    
    public org.jboss.test.ws.jaxws.jsr181.complex.client.InvoiceCustomer getInvoiceCustomer() {
        return invoiceCustomer;
    }
    
    public void setInvoiceCustomer(org.jboss.test.ws.jaxws.jsr181.complex.client.InvoiceCustomer invoiceCustomer) {
        this.invoiceCustomer = invoiceCustomer;
    }
}
