// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class RegisterResponse {
    protected long registeredID;
    
    public RegisterResponse() {
    }
    
    public RegisterResponse(long registeredID) {
        this.registeredID = registeredID;
    }
    
    public long getRegisteredID() {
        return registeredID;
    }
    
    public void setRegisteredID(long registeredID) {
        this.registeredID = registeredID;
    }
}
