// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class RegisterForInvoiceResponse {
    protected boolean done;
    
    public RegisterForInvoiceResponse() {
    }
    
    public RegisterForInvoiceResponse(boolean done) {
        this.done = done;
    }
    
    public boolean isDone() {
        return done;
    }
    
    public void setDone(boolean done) {
        this.done = done;
    }
}
