// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;


public class Register {
    protected org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer;
    protected java.util.Calendar when;
    
    public Register() {
    }
    
    public Register(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer, java.util.Calendar when) {
        this.customer = customer;
        this.when = when;
    }
    
    public org.jboss.test.ws.jaxws.jsr181.complex.client.Customer getCustomer() {
        return customer;
    }
    
    public void setCustomer(org.jboss.test.ws.jaxws.jsr181.complex.client.Customer customer) {
        this.customer = customer;
    }
    
    public java.util.Calendar getWhen() {
        return when;
    }
    
    public void setWhen(java.util.Calendar when) {
        this.when = when;
    }
}
