// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;

import javax.xml.rpc.Service;
import javax.xml.rpc.ServiceException;

public interface RegistrationServiceService extends Service
{
   public RegistrationService getRegistrationServicePort() throws ServiceException;
}
