// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxws.jsr181.complex.client;

import java.util.Calendar;


public class Statistics {
    protected Calendar activationTime;
    protected long hits;
    
    public Statistics() {
    }
    
    public Statistics(Calendar activationTime, long hits) {
        this.activationTime = activationTime;
        this.hits = hits;
    }
    
    public Calendar getActivationTime() {
        return activationTime;
    }
    
    public void setActivationTime(Calendar activationTime) {
        this.activationTime = activationTime;
    }
    
    public long getHits() {
        return hits;
    }
    
    public void setHits(long hits) {
        this.hits = hits;
    }
}
