// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.userexception;

import javax.xml.rpc.*;

public interface UserExceptionService extends javax.xml.rpc.Service {
    public org.jboss.test.webservice.userexception.UserExceptionSEI getUserExceptionSEIPort() throws ServiceException;
}
