// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.userexception;


public class MyFaultType extends java.lang.Exception {
    private java.lang.String message;
    
    
    public MyFaultType(java.lang.String message) {
        super(message);
        this.message = message;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
}
