// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1455;

public interface TestEndpoint_PortType extends java.rmi.Remote {
    public java.lang.String methodOne(java.lang.String parameters) throws 
         java.rmi.RemoteException;
    public java.lang.String methodTwo(java.lang.String parameters) throws 
        org.jboss.test.ws.jbws1455.MyException,  java.rmi.RemoteException;
}
