// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class GlobalPrice {
    protected java.lang.String currency;
    protected java.math.BigDecimal _value;

    public GlobalPrice() {
    }

    public GlobalPrice(java.lang.String currency, java.math.BigDecimal _value) {        this.currency = currency;
        this._value = _value;
    }

    public java.lang.String getCurrency() {
        return currency;
    } 

    public void setCurrency(java.lang.String currency) {
        this.currency = currency;
    }

    public java.math.BigDecimal get_value() {
        return _value;
    }

    public void set_value(java.math.BigDecimal _value) {
        this._value = _value;
    }
}