// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt;


public class EchoResponse {
    protected java.lang.String echoResult;
    
    public EchoResponse() {
    }
        
    public EchoResponse(java.lang.String echoResult) {
        this.echoResult = echoResult;
    }
    
    public java.lang.String getEchoResult() {
        return echoResult;
    }
    
    public void setEchoResult(java.lang.String echoResult) {
        this.echoResult = echoResult;
    }
}
