// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt;

public interface IPingService extends java.rmi.Remote {
    public org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt.PingResponseType ping(org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt.PingType parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt.EchoResponse echo(org.jboss.test.ws.interop.microsoft.security.wsse10Encrypt.Echo parameters) throws 
         java.rmi.RemoteException;
}
