// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;

public interface IBaseDataTypesDocLitW extends java.rmi.Remote {
    public java.lang.Boolean retBool(java.lang.Boolean inBool) throws 
         java.rmi.RemoteException;
    public short retByte(short inByte) throws 
         java.rmi.RemoteException;
    public java.lang.Byte retSByte(java.lang.Byte inSByte) throws 
         java.rmi.RemoteException;
    public byte[] retByteArray(byte[] inByteArray) throws 
         java.rmi.RemoteException;
    public java.lang.Integer retChar(java.lang.Integer inChar) throws 
         java.rmi.RemoteException;
    public java.math.BigDecimal retDecimal(java.math.BigDecimal inDecimal) throws 
         java.rmi.RemoteException;
    public java.lang.Float retFloat(java.lang.Float inFloat) throws 
         java.rmi.RemoteException;
    public java.lang.Double retDouble(java.lang.Double inDouble) throws 
         java.rmi.RemoteException;
    public java.lang.Float retSingle(java.lang.Float inSingle) throws 
         java.rmi.RemoteException;
    public java.lang.Integer retInt(java.lang.Integer inInt) throws 
         java.rmi.RemoteException;
    public java.lang.Short retShort(java.lang.Short inShort) throws 
         java.rmi.RemoteException;
    public java.lang.Long retLong(java.lang.Long inLong) throws 
         java.rmi.RemoteException;
    public javax.xml.soap.SOAPElement retObject(javax.xml.soap.SOAPElement inObject) throws 
         java.rmi.RemoteException;
    public long retUInt(long inUInt) throws 
         java.rmi.RemoteException;
    public int retUShort(int inUShort) throws 
         java.rmi.RemoteException;
    public java.math.BigInteger retULong(java.math.BigInteger inULong) throws 
         java.rmi.RemoteException;
    public java.lang.String retString(java.lang.String inString) throws 
         java.rmi.RemoteException;
    public java.lang.String retGuid(java.lang.String inGuid) throws 
         java.rmi.RemoteException;
    public java.net.URI retUri(java.net.URI inUri) throws 
         java.rmi.RemoteException;
    public java.util.Calendar retDateTime(java.util.Calendar inDateTime) throws 
         java.rmi.RemoteException;
    public java.lang.String retTimeSpan(java.lang.String inTimeSpan) throws 
         java.rmi.RemoteException;
    public javax.xml.namespace.QName retQName(javax.xml.namespace.QName inQName) throws 
         java.rmi.RemoteException;
}
