// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetByte {
    protected short inByte;
    
    public RetByte() {
    }
    
    public RetByte(short inByte) {
        this.inByte = inByte;
    }
    
    public short getInByte() {
        return inByte;
    }
    
    public void setInByte(short inByte) {
        this.inByte = inByte;
    }
}
