// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetByteResponse {
    protected short retByteResult;
    
    public RetByteResponse() {
    }
    
    public RetByteResponse(short retByteResult) {
        this.retByteResult = retByteResult;
    }
    
    public short getRetByteResult() {
        return retByteResult;
    }
    
    public void setRetByteResult(short retByteResult) {
        this.retByteResult = retByteResult;
    }
}
