// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetCharResponse {
    protected java.lang.Integer retCharResult;
    
    public RetCharResponse() {
    }
    
    public RetCharResponse(java.lang.Integer retCharResult) {
        this.retCharResult = retCharResult;
    }
    
    public java.lang.Integer getRetCharResult() {
        return retCharResult;
    }
    
    public void setRetCharResult(java.lang.Integer retCharResult) {
        this.retCharResult = retCharResult;
    }
}
