// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetDecimalResponse {
    protected java.math.BigDecimal retDecimalResult;
    
    public RetDecimalResponse() {
    }
    
    public RetDecimalResponse(java.math.BigDecimal retDecimalResult) {
        this.retDecimalResult = retDecimalResult;
    }
    
    public java.math.BigDecimal getRetDecimalResult() {
        return retDecimalResult;
    }
    
    public void setRetDecimalResult(java.math.BigDecimal retDecimalResult) {
        this.retDecimalResult = retDecimalResult;
    }
}
