// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetDouble {
    protected java.lang.Double inDouble;
    
    public RetDouble() {
    }
    
    public RetDouble(java.lang.Double inDouble) {
        this.inDouble = inDouble;
    }
    
    public java.lang.Double getInDouble() {
        return inDouble;
    }
    
    public void setInDouble(java.lang.Double inDouble) {
        this.inDouble = inDouble;
    }
}
