// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetLongResponse {
    protected java.lang.Long retLongResult;
    
    public RetLongResponse() {
    }
    
    public RetLongResponse(java.lang.Long retLongResult) {
        this.retLongResult = retLongResult;
    }
    
    public java.lang.Long getRetLongResult() {
        return retLongResult;
    }
    
    public void setRetLongResult(java.lang.Long retLongResult) {
        this.retLongResult = retLongResult;
    }
}
