// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetObject {
    protected javax.xml.soap.SOAPElement inObject;
    
    public RetObject() {
    }
    
    public RetObject(javax.xml.soap.SOAPElement inObject) {
        this.inObject = inObject;
    }
    
    public javax.xml.soap.SOAPElement getInObject() {
        return inObject;
    }
    
    public void setInObject(javax.xml.soap.SOAPElement inObject) {
        this.inObject = inObject;
    }
}
