// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetSingleResponse {
    protected java.lang.Float retSingleResult;
    
    public RetSingleResponse() {
    }
    
    public RetSingleResponse(java.lang.Float retSingleResult) {
        this.retSingleResult = retSingleResult;
    }
    
    public java.lang.Float getRetSingleResult() {
        return retSingleResult;
    }
    
    public void setRetSingleResult(java.lang.Float retSingleResult) {
        this.retSingleResult = retSingleResult;
    }
}
