// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetShort {
    protected java.lang.Short inShort;
    
    public RetShort() {
    }
    
    public RetShort(java.lang.Short inShort) {
        this.inShort = inShort;
    }
    
    public java.lang.Short getInShort() {
        return inShort;
    }
    
    public void setInShort(java.lang.Short inShort) {
        this.inShort = inShort;
    }
}
