// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetSingle {
    protected java.lang.Float inSingle;
    
    public RetSingle() {
    }
    
    public RetSingle(java.lang.Float inSingle) {
        this.inSingle = inSingle;
    }
    
    public java.lang.Float getInSingle() {
        return inSingle;
    }
    
    public void setInSingle(java.lang.Float inSingle) {
        this.inSingle = inSingle;
    }
}
