// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetSByte {
    protected java.lang.Byte inSByte;
    
    public RetSByte() {
    }
    
    public RetSByte(java.lang.Byte inSByte) {
        this.inSByte = inSByte;
    }
    
    public java.lang.Byte getInSByte() {
        return inSByte;
    }
    
    public void setInSByte(java.lang.Byte inSByte) {
        this.inSByte = inSByte;
    }
}
