// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetString {
    protected java.lang.String inString;
    
    public RetString() {
    }
    
    public RetString(java.lang.String inString) {
        this.inString = inString;
    }
    
    public java.lang.String getInString() {
        return inString;
    }
    
    public void setInString(java.lang.String inString) {
        this.inString = inString;
    }
}
