// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetTimeSpan {
    protected java.lang.String inTimeSpan;
    
    public RetTimeSpan() {
    }
    
    public RetTimeSpan(java.lang.String inTimeSpan) {
        this.inTimeSpan = inTimeSpan;
    }
    
    public java.lang.String getInTimeSpan() {
        return inTimeSpan;
    }
    
    public void setInTimeSpan(java.lang.String inTimeSpan) {
        this.inTimeSpan = inTimeSpan;
    }
}
