// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetUri {
    protected java.net.URI inUri;
    
    public RetUri() {
    }
    
    public RetUri(java.net.URI inUri) {
        this.inUri = inUri;
    }
    
    public java.net.URI getInUri() {
        return inUri;
    }
    
    public void setInUri(java.net.URI inUri) {
        this.inUri = inUri;
    }
}
