// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.soapwsdl.BaseDataTypesDocLitW_Service;


public class RetUInt {
    protected long inUInt;
    
    public RetUInt() {
    }
    
    public RetUInt(long inUInt) {
        this.inUInt = inUInt;
    }
    
    public long getInUInt() {
        return inUInt;
    }
    
    public void setInUInt(long inUInt) {
        this.inUInt = inUInt;
    }
}
