// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class TypicalPerson {
    protected java.lang.String name;
    protected java.math.BigInteger age;
    protected java.lang.String userId;
    protected java.lang.String password;
    protected org.jboss.ws.types.USMidwest state;

    public TypicalPerson() {
    }

     public TypicalPerson(java.lang.String name, java.math.BigInteger age, java.lang.String userId, java.lang.String password) {
        this.name = name;
        this.age = age;
        this.userId = userId;
        this.password = password;
    }

    public java.lang.String getName() {
        return name;
    }

    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.math.BigInteger getAge() {
        return age;
    }

    public void setAge(java.math.BigInteger age) {
        this.age = age;
    }

    public java.lang.String getUserId() {
        return userId;
    }

    public void setUserId(java.lang.String userId) {
        this.userId = userId;
    }

    public java.lang.String getPassword() {
        return password;
    }

    public void setPassword(java.lang.String password) {
        this.password = password;
    }

    public org.jboss.ws.types.USMidwest getState() {
        return state;
    }

    public void setState(org.jboss.ws.types.USMidwest state) {
        this.state = state;
    }
}