// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.userexception;

public interface UserExceptionSEI extends java.rmi.Remote {
    public void testCustomException() throws 
        org.jboss.test.webservice.userexception.CustomException,  java.rmi.RemoteException;
    public void testUserException(java.lang.String string_1) throws 
        org.jboss.test.webservice.userexception.MyException,  java.rmi.RemoteException;
    public void testAnonymousException(java.lang.String string_1) throws 
        org.jboss.test.webservice.userexception.AnonymousException,  java.rmi.RemoteException;
    public void testMyFaultType() throws 
        org.jboss.test.webservice.userexception.MyFaultType,  java.rmi.RemoteException;
}
