// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class Teacher {
    protected java.lang.String firstname;
    protected java.lang.String lastname;
    protected java.util.Calendar birthday;

    public Teacher() {
    }

    public Teacher(java.lang.String firstname, java.lang.String lastname, java.util.Calendar birthday) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.birthday = birthday;
    }

    public java.lang.String getFirstname() {
        return firstname;
    }

    public void setFirstname(java.lang.String firstname) {
        this.firstname = firstname;
    }

    public java.lang.String getLastname() {
        return lastname;
    }

    public void setLastname(java.lang.String lastname) {
        this.lastname = lastname;
    }

    public java.util.Calendar getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Calendar birthday) {
        this.birthday = birthday;
    }
}