/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.jbws807;


public class  PingMsg
{

    protected java.lang.String message;
    public PingMsg(){}

    public PingMsg(java.lang.String message){
        this.message=message;
    }
    public java.lang.String getMessage() { return message ;}

    public void setMessage(java.lang.String message){ this.message=message; }

}
