/*  
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org. 
 */
//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jaxrpc.jbws807;
public interface  TestService_PortType extends java.rmi.Remote
{

  public org.jboss.test.ws.jaxrpc.jbws807.PingMsgResponse  ping(org.jboss.test.ws.jaxrpc.jbws807.PingMsg pingMsg) throws  java.rmi.RemoteException;
}
