// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.oneway;

import javax.xml.rpc.*;

public interface OneWayService extends javax.xml.rpc.Service {
    public org.jboss.test.webservice.oneway.TestOneWaySEI getTestOneWaySEIPort() throws ServiceException;
}
