/*
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org.
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.wsse;


public class  JaxRpcTestService_echoSimpleUserType_ResponseStruct
{

protected SimpleUserType result;
public JaxRpcTestService_echoSimpleUserType_ResponseStruct(){}

public JaxRpcTestService_echoSimpleUserType_ResponseStruct(SimpleUserType result){
this.result=result;
}
public SimpleUserType getResult() { return result ;}

public void setResult(SimpleUserType myvar ){  result=myvar ;}

}
