// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class ArrayOfbase64Binary {
    protected byte[][] base64Binary;
    
    public ArrayOfbase64Binary() {
    }
    
    public ArrayOfbase64Binary(byte[][] base64Binary) {
        this.base64Binary = base64Binary;
    }
    
    public byte[][] getBase64Binary() {
        return base64Binary;
    }
    
    public void setBase64Binary(byte[][] base64Binary) {
        this.base64Binary = base64Binary;
    }
}
