// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class ArrayOfstring {
    protected java.lang.String[] string;
    
    public ArrayOfstring() {
    }
    
    public ArrayOfstring(java.lang.String[] string) {
        this.string = string;
    }
    
    public java.lang.String[] getString() {
        return string;
    }
    
    public void setString(java.lang.String[] string) {
        this.string = string;
    }
}
