// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoBinaryAsStringResponse {
    protected java.lang.String echoBinaryAsStringResult;
    
    public EchoBinaryAsStringResponse() {
    }
    
    public EchoBinaryAsStringResponse(java.lang.String echoBinaryAsStringResult) {
        this.echoBinaryAsStringResult = echoBinaryAsStringResult;
    }
    
    public java.lang.String getEchoBinaryAsStringResult() {
        return echoBinaryAsStringResult;
    }
    
    public void setEchoBinaryAsStringResult(java.lang.String echoBinaryAsStringResult) {
        this.echoBinaryAsStringResult = echoBinaryAsStringResult;
    }
}
