// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoBinaryFieldAsStringResponse {
    protected java.lang.String echoBinaryFieldAsStringResult;
    
    public EchoBinaryFieldAsStringResponse() {
    }
    
    public EchoBinaryFieldAsStringResponse(java.lang.String echoBinaryFieldAsStringResult) {
        this.echoBinaryFieldAsStringResult = echoBinaryFieldAsStringResult;
    }
    
    public java.lang.String getEchoBinaryFieldAsStringResult() {
        return echoBinaryFieldAsStringResult;
    }
    
    public void setEchoBinaryFieldAsStringResult(java.lang.String echoBinaryFieldAsStringResult) {
        this.echoBinaryFieldAsStringResult = echoBinaryFieldAsStringResult;
    }
}
