// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoBinaryFieldAsString {
    protected org.jboss.test.ws.interop.microsoft.mtom.utf8.MtomTestStruct s;
    
    public EchoBinaryFieldAsString() {
    }
    
    public EchoBinaryFieldAsString(org.jboss.test.ws.interop.microsoft.mtom.utf8.MtomTestStruct s) {
        this.s = s;
    }
    
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.MtomTestStruct getS() {
        return s;
    }
    
    public void setS(org.jboss.test.ws.interop.microsoft.mtom.utf8.MtomTestStruct s) {
        this.s = s;
    }
}
