// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoStringAsBinary {
    protected java.lang.String s;
    
    public EchoStringAsBinary() {
    }
    
    public EchoStringAsBinary(java.lang.String s) {
        this.s = s;
    }
    
    public java.lang.String getS() {
        return s;
    }
    
    public void setS(java.lang.String s) {
        this.s = s;
    }
}
