// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoBinaryArrayAsStringArrayResponse {
    protected org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfstring echoBinaryArrayAsStringArrayResult;
    
    public EchoBinaryArrayAsStringArrayResponse() {
    }
    
    public EchoBinaryArrayAsStringArrayResponse(org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfstring echoBinaryArrayAsStringArrayResult) {
        this.echoBinaryArrayAsStringArrayResult = echoBinaryArrayAsStringArrayResult;
    }
    
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfstring getEchoBinaryArrayAsStringArrayResult() {
        return echoBinaryArrayAsStringArrayResult;
    }
    
    public void setEchoBinaryArrayAsStringArrayResult(org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfstring echoBinaryArrayAsStringArrayResult) {
        this.echoBinaryArrayAsStringArrayResult = echoBinaryArrayAsStringArrayResult;
    }
}
