// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoBinaryArrayAsStringArray {
    protected org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfbase64Binary arrayOfArray;
    
    public EchoBinaryArrayAsStringArray() {
    }
    
    public EchoBinaryArrayAsStringArray(org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfbase64Binary arrayOfArray) {
        this.arrayOfArray = arrayOfArray;
    }
    
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfbase64Binary getArrayOfArray() {
        return arrayOfArray;
    }
    
    public void setArrayOfArray(org.jboss.test.ws.interop.microsoft.mtom.utf8.ArrayOfbase64Binary arrayOfArray) {
        this.arrayOfArray = arrayOfArray;
    }
}
