// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class EchoStringAsBinaryResponse {
    protected byte[] echoStringAsBinaryResult;
    
    public EchoStringAsBinaryResponse() {
    }
    
    public EchoStringAsBinaryResponse(byte[] echoStringAsBinaryResult) {
        this.echoStringAsBinaryResult = echoStringAsBinaryResult;
    }
    
    public byte[] getEchoStringAsBinaryResult() {
        return echoStringAsBinaryResult;
    }
    
    public void setEchoStringAsBinaryResult(byte[] echoStringAsBinaryResult) {
        this.echoStringAsBinaryResult = echoStringAsBinaryResult;
    }
}
