// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;

public interface IMtomTest extends java.rmi.Remote {
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryAsStringResponse echoBinaryAsString(org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryAsString parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoStringAsBinaryResponse echoStringAsBinary(org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoStringAsBinary parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryArrayAsStringArrayResponse echoBinaryArrayAsStringArray(org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryArrayAsStringArray parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryFieldAsStringResponse echoBinaryFieldAsString(org.jboss.test.ws.interop.microsoft.mtom.utf8.EchoBinaryFieldAsString parameters) throws 
         java.rmi.RemoteException;
    public org.jboss.test.ws.interop.microsoft.mtom.utf8.OutputMessageContract echoBinaryHeaderAsString(org.jboss.test.ws.interop.microsoft.mtom.utf8.InputMessageContract parameters) throws 
         java.rmi.RemoteException;
}
