// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.mtom.utf8;


public class MtomTestStruct {
    protected byte[] array;
    protected java.lang.String name;
    
    public MtomTestStruct() {
    }
    
    public MtomTestStruct(byte[] array, java.lang.String name) {
        this.array = array;
        this.name = name;
    }
    
    public byte[] getArray() {
        return array;
    }
    
    public void setArray(byte[] array) {
        this.array = array;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
}
