// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class LookupResponse {
    protected org.jboss.test.ws.jbws1260.Telephone[] number;
    
    public LookupResponse() {
    }
    
    public LookupResponse(org.jboss.test.ws.jbws1260.Telephone[] number) {
        this.number = number;
    }
    
    public org.jboss.test.ws.jbws1260.Telephone[] getNumber() {
        return number;
    }
    
    public void setNumber(org.jboss.test.ws.jbws1260.Telephone[] number) {
        this.number = number;
    }
}
