// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class Lookup {
    protected java.lang.String surname;
    
    public Lookup() {
    }
    
    public Lookup(java.lang.String surname) {
        this.surname = surname;
    }
    
    public java.lang.String getSurname() {
        return surname;
    }
    
    public void setSurname(java.lang.String surname) {
        this.surname = surname;
    }
}
