// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.outparameters;

public interface OutParametersService_PortType extends java.rmi.Remote {
    public void echoOut(javax.xml.rpc.holders.BigDecimalHolder bigDecimal_1, javax.xml.rpc.holders.CalendarHolder calendar_2, javax.xml.rpc.holders.StringHolder string_3) throws 
         java.rmi.RemoteException;
}
