// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jaxrpc.encoded.href;

import org.jboss.logging.Logger;

public class MarshallTestImpl implements MarshallTest
{
   // Provide logging
   private static Logger log = Logger.getLogger(MarshallTestImpl.class);

   public byte[] base64BinaryTest(byte[] byteArray)
   {
      String message = new String(byteArray);
      log.info("base64BinaryTest: " + message);
      
      if (message == null && message.length() == 0)
         throw new IllegalStateException("Incommig message is null");
      
      HRefHandler.setHrefEncoding("HrefEncodedRequest".equals(message));
      return byteArray;
   }
}
