// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.webservice.inoutparameters;

public interface InOutParametersService_PortType extends java.rmi.Remote {
    public void echoInOut(javax.xml.rpc.holders.BigDecimalHolder bigDecimal_1, javax.xml.rpc.holders.CalendarHolder calendar_2) throws 
         java.rmi.RemoteException;
}
