// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1260;


public class Person {
    protected org.jboss.test.ws.jbws1260.LookupName name;
    
    public Person() {
    }
    
    public Person(org.jboss.test.ws.jbws1260.LookupName name) {
        this.name = name;
    }
    
    public org.jboss.test.ws.jbws1260.LookupName getName() {
        return name;
    }
    
    public void setName(org.jboss.test.ws.jbws1260.LookupName name) {
        this.name = name;
    }
}
