// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class AwardEmployee extends org.jboss.ws.types.Employee {
    protected java.lang.String awardWon;

    public AwardEmployee() {
    }

    public AwardEmployee(java.lang.String name, java.lang.String role, java.lang.String boss, java.lang.String awardWon) {
        this.name = name;
        this.role = role;
        this.boss = boss;
        this.awardWon = awardWon;
    }

    public java.lang.String getAwardWon() {
        return awardWon;
    }

    public void setAwardWon(java.lang.String awardWon) {
        this.awardWon = awardWon;
    }
}
