// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.jbws1184;


public class DataObject {
    protected boolean booleanValue;
    protected byte byteValue;
    protected float floatValue;
    protected int integerValue;
    protected long longValue;
    protected short shortValue;
    
    public DataObject() {
    }
    
    public DataObject(boolean booleanValue, byte byteValue, float floatValue, int integerValue, long longValue, short shortValue) {
        this.booleanValue = booleanValue;
        this.byteValue = byteValue;
        this.floatValue = floatValue;
        this.integerValue = integerValue;
        this.longValue = longValue;
        this.shortValue = shortValue;
    }
    
    public boolean isBooleanValue() {
        return booleanValue;
    }
    
    public void setBooleanValue(boolean booleanValue) {
        this.booleanValue = booleanValue;
    }
    
    public byte getByteValue() {
        return byteValue;
    }
    
    public void setByteValue(byte byteValue) {
        this.byteValue = byteValue;
    }
    
    public float getFloatValue() {
        return floatValue;
    }
    
    public void setFloatValue(float floatValue) {
        this.floatValue = floatValue;
    }
    
    public int getIntegerValue() {
        return integerValue;
    }
    
    public void setIntegerValue(int integerValue) {
        this.integerValue = integerValue;
    }
    
    public long getLongValue() {
        return longValue;
    }
    
    public void setLongValue(long longValue) {
        this.longValue = longValue;
    }
    
    public short getShortValue() {
        return shortValue;
    }
    
    public void setShortValue(short shortValue) {
        this.shortValue = shortValue;
    }
}
