// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.addressing.wsa10;

public interface Notify extends java.rmi.Remote {
    public void notify(java.lang.String notify) throws 
         java.rmi.RemoteException;
}
