// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package org.jboss.test.ws.interop.microsoft.addressing.wsa10;

import javax.xml.rpc.*;

public interface WSAddressingCR extends javax.xml.rpc.Service {
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Notify getCustomBinding_Notify() throws ServiceException;
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo getCustomBinding_Echo() throws ServiceException;
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo2 getCustomBinding_Echo2() throws ServiceException;
    public org.jboss.test.ws.interop.microsoft.addressing.wsa10.Echo4 getCustomBinding_Echo4() throws ServiceException;
}
