/*
 * JBoss, the OpenSource EJB server
 * Distributable under LGPL license. See terms of license at gnu.org.
 */
//Auto Generated by jbossws - Please do not edit!!!


package org.jboss.test.ws.jaxrpc.jbws807;


public class  PingMsgResponse
{
    public PingMsgResponse(){
    }
}
