/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.jbpapp921;


import javax.xml.rpc.*; 


public interface  Models_ServiceIM_ServiceProxyService extends  javax.xml.rpc.Service
{

     public org.jboss.test.ws.jbpapp921.ValidationEvent_test getvalidationEventPort() throws ServiceException;

}
