/*  
* JBoss, the OpenSource EJB server
* Distributable under LGPL license. See terms of license at gnu.org.
*/

//Auto Generated by jbossws - Please do not edit!!!

package org.jboss.test.ws.interop.microsoft.addressing.sep06.wsa10;


import javax.xml.rpc.*; 


public interface  WSAddressingCR extends javax.xml.rpc.Service
{

     public org.jboss.test.ws.interop.microsoft.addressing.sep06.wsa10.Echo getCustomBinding_Echo() throws ServiceException;

     public org.jboss.test.ws.interop.microsoft.addressing.sep06.wsa10.Notify getCustomBinding_Notify() throws ServiceException;

     public org.jboss.test.ws.interop.microsoft.addressing.sep06.wsa10.Echo getCustomBinding_Echo4() throws ServiceException;

     public org.jboss.test.ws.interop.microsoft.addressing.sep06.wsa10.Echo getCustomBinding_Echo2() throws ServiceException;

}
