<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ReqResService" targetNamespace="http://org.jboss.ws/jaxws/wsrm" xmlns:tns="http://org.jboss.ws/jaxws/wsrm" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
  </types>
  <message name="ReqRes_echo">
    <part name="String_1" type="xsd:string">
    </part>
  </message>
  <message name="ReqRes_echoResponse">
    <part name="result" type="xsd:string">
    </part>
  </message>
  <portType name="ReqRes">
    <operation name="echo" parameterOrder="String_1">
      <input message="tns:ReqRes_echo">
    </input>
      <output message="tns:ReqRes_echoResponse">
    </output>
    </operation>
  </portType>
  <binding name="ReqResBinding" type="tns:ReqRes">
    <wsp:PolicyReference URI="#exactly_one_in_order_rm_delivery"/>
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="echo">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal" namespace="http://org.jboss.ws/jaxws/wsrm"/>
      </input>
      <output>
        <soap:body use="literal" namespace="http://org.jboss.ws/jaxws/wsrm"/>
      </output>
    </operation>
  </binding>
  <service name="ReqResService">
    <port name="ReqResPort" binding="tns:ReqResBinding">
      <soap:address location="http://127.0.0.1:8080/jaxws-wsrm-emulator/ReqResService"/>
    </port>
  </service>
    <wsp:Policy wsu:Id="exactly_one_in_order_rm_delivery" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <wsp:All>
   <wsrmp:DeliveryAssurance xmlns:wsrmp="http://docs.oasis-open.org/ws-rx/wsrmp/200702">
    <wsp:Policy>
     <wsp:ExactlyOne>
      <wsp:All>
       <wsrmp:ExactlyOnce/>
       <wsrmp:InOrder/>
      </wsp:All>
     </wsp:ExactlyOne>
    </wsp:Policy>
   </wsrmp:DeliveryAssurance>
  </wsp:All>
 </wsp:Policy>
</definitions>
