
package org.jboss.test.ws.jaxws.webserviceref;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "TestEndpointService", targetNamespace = "http://org.jboss.ws/wsref", wsdlLocation = "META-INF/wsdl/TestEndpoint.wsdl")
public class TestEndpointService
    extends Service
{

    private final static URL TESTENDPOINTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:./resources/jaxws/webserviceref/META-INF/wsdl/TestEndpoint.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        TESTENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public TestEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestEndpointService() {
        super(TESTENDPOINTSERVICE_WSDL_LOCATION, new QName("http://org.jboss.ws/wsref", "TestEndpointService"));
    }

    /**
     * 
     * @return
     *     returns TestEndpoint
     */
    @WebEndpoint(name = "TestEndpointPort")
    public TestEndpoint getTestEndpointPort() {
        return (TestEndpoint)super.getPort(new QName("http://org.jboss.ws/wsref", "TestEndpointPort"), TestEndpoint.class);
    }

}
