
package org.jboss.test.ws.jaxws.webserviceref;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_01-b59-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "TestEndpoint", targetNamespace = "http://org.jboss.ws/wsref")
public interface TestEndpoint {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://org.jboss.ws/wsref")
    @RequestWrapper(localName = "echo", targetNamespace = "http://org.jboss.ws/wsref", className = "org.jboss.test.ws.jaxws.webserviceref.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://org.jboss.ws/wsref", className = "org.jboss.test.ws.jaxws.webserviceref.EchoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "http://org.jboss.ws/wsref")
        String arg0);

}
