// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.2_01, build R40)
// Generated source version: 1.1.2

package org.jboss.ws.types;


public class Items {
    protected org.jboss.ws.types.ItemsItem[] item;

    public Items() {
    }

    public Items(org.jboss.ws.types.ItemsItem[] item) {
        this.item = item;
    }

    public org.jboss.ws.types.ItemsItem[] getItem() {
        return item;
    }

    public void setItem(org.jboss.ws.types.ItemsItem[] item) {
        this.item = item;
    }
}